// @generated by vvm-build. Do not edit.

#[cxx::bridge(namespace = "vvm::packed_enum_ports")]
/// Raw generated FFI bindings for the Verilated DUT adapter.
mod ffi {
    unsafe extern "C++" {
        include!("packed_enum_ports.hpp");

        /// Opaque generated Verilated DUT adapter.
        type PackedEnumPorts;

        /// Constructs a Verilated DUT adapter.
        fn create_packed_enum_ports() -> UniquePtr<PackedEnumPorts>;

        /// Evaluates the current DUT state.
        fn eval(self: Pin<&mut PackedEnumPorts>);

        /// Advances the native simulation context time.
        fn advance_time(self: Pin<&mut PackedEnumPorts>, delta: u64) -> bool;

        /// Finalises the DUT model.
        fn finish(self: Pin<&mut PackedEnumPorts>);

        /// Drives the `clk` DUT input.
        fn set_clk(self: Pin<&mut PackedEnumPorts>, value: bool);

        /// Drives the `state` DUT input.
        fn set_state(self: Pin<&mut PackedEnumPorts>, value: u8);

        /// Samples the `state_out` DUT output.
        fn state_out(self: &PackedEnumPorts) -> u8;

        /// Samples the `state_raw_out` DUT output.
        fn state_raw_out(self: &PackedEnumPorts) -> u8;

        /// Drives the `signed_state` DUT input.
        fn set_signed_state(self: Pin<&mut PackedEnumPorts>, value: i8);

        /// Samples the `signed_state_out` DUT output.
        fn signed_state_out(self: &PackedEnumPorts) -> i8;

        /// Samples the `signed_state_raw_out` DUT output.
        fn signed_state_raw_out(self: &PackedEnumPorts) -> i8;
    }
}
