// @generated by vvm-build. Do not edit.

include!(concat!(
    env!("OUT_DIR"),
    "/vvm/packed_enum_ports/generated/bridge.rs"
));

/// Declared HDL variants of [`State`].
#[allow(non_camel_case_types)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum StateVariant {
    STATE_IDLE,
    STATE_BUSY,
    STATE_DONE,
    STATE_ERROR,
}

impl StateVariant {
    /// Returns the canonical raw HDL discriminant.
    #[must_use]
    pub const fn raw(self) -> u64 {
        match self {
            Self::STATE_IDLE => 0,
            Self::STATE_BUSY => 2,
            Self::STATE_DONE => 5,
            Self::STATE_ERROR => 7,
        }
    }

    /// Returns the original HDL variant name.
    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
            Self::STATE_IDLE => "STATE_IDLE",
            Self::STATE_BUSY => "STATE_BUSY",
            Self::STATE_DONE => "STATE_DONE",
            Self::STATE_ERROR => "STATE_ERROR",
        }
    }
}

/// Packed-enum value used by the `state` DUT port.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct State {
    /// Canonical flattened packed storage.
    bits: ::vvm::Bits<3>,
}

#[allow(clippy::same_name_method)]
impl State {
    /// Total packed width.
    pub const WIDTH: usize = 3;

    /// Number of canonical transfer words.
    pub const WORDS: usize = ::vvm::Bits::<3>::WORDS;

    /// Declared enum variants in HDL declaration order.
    pub const VARIANTS: &'static [::vvm::PackedEnumVariantLayout] = &[
        ::vvm::PackedEnumVariantLayout::new("STATE_IDLE", 0),
        ::vvm::PackedEnumVariantLayout::new("STATE_BUSY", 2),
        ::vvm::PackedEnumVariantLayout::new("STATE_DONE", 5),
        ::vvm::PackedEnumVariantLayout::new("STATE_ERROR", 7),
    ];

    /// Complete packed-enum layout.
    pub const LAYOUT: ::vvm::PackedEnumLayout =
        ::vvm::PackedEnumLayout::new("State", Self::WIDTH, false, Self::VARIANTS);

    /// Constructs an all-zero packed-enum value.
    #[must_use]
    pub fn zero() -> Self {
        Self {
            bits: ::vvm::Bits::<3>::zero(),
        }
    }

    /// Wraps canonical packed bits.
    #[must_use]
    pub const fn from_bits(bits: ::vvm::Bits<3>) -> Self {
        Self {
            bits,
        }
    }

    /// Returns the underlying packed bits.
    #[must_use]
    pub const fn bits(&self) -> &::vvm::Bits<3> {
        &self.bits
    }

    /// Returns the packed width.
    #[must_use]
    pub const fn width() -> usize {
        Self::WIDTH
    }

    /// Returns the packed-enum layout.
    #[must_use]
    pub const fn layout() -> ::vvm::PackedEnumLayout {
        Self::LAYOUT
    }

    /// Returns declared HDL variants in declaration order.
    #[must_use]
    pub const fn variants() -> &'static [::vvm::PackedEnumVariantLayout] {
        Self::VARIANTS
    }

    /// Consumes the value and returns its packed bits.
    #[must_use]
    pub fn into_bits(self) -> ::vvm::Bits<3> {
        self.bits
    }

    /// Constructs the packed enum from canonical words.
    ///
    /// # Errors
    ///
    /// Returns an error when the word count does not match the packed width.
    pub fn from_words_le(
        words: impl AsRef<[u32]>,
    ) -> std::result::Result<Self, ::vvm::InvalidBitVectorWordCount> {
        ::vvm::Bits::<3>::from_words_le(words)
            .map(Self::from_bits)
    }

    /// Returns canonical least-significant-word-first words.
    #[must_use]
    pub fn words_le(&self) -> &[u32] {
        self.bits.words_le()
    }

    /// Constructs a packed-enum value from its raw bit pattern.
    ///
    /// Only the low [`Self::WIDTH`] bits are retained.
    #[must_use]
    pub fn from_raw(value: u64) -> Self {
        Self::from_bits(::vvm::Bits::<3>::from(value))
    }

    /// Returns the canonical raw enum bit pattern.
    ///
    /// # Errors
    ///
    /// Returns an error if the internal packed storage cannot be extracted.
    pub fn raw(&self) -> std::result::Result<u64, ::vvm::PackedLayoutError> {
        ::vvm::extract_unsigned(
            self.words_le(),
            Self::WIDTH,
            0,
            Self::WIDTH,
        )
    }

    /// Constructs a packed value from one declared HDL variant.
    #[must_use]
    pub fn from_variant(variant: StateVariant) -> Self {
        Self::from_raw(variant.raw())
    }

    /// Returns the declared variant matching this raw value.
    ///
    /// Unknown but valid HDL bit patterns return `None`.
    ///
    /// # Errors
    ///
    /// Returns an error if packed storage extraction fails.
    pub fn variant(&self) -> std::result::Result<Option<StateVariant>, ::vvm::PackedLayoutError> {
        let variant = match self.raw()? {
            0 => Some(StateVariant::STATE_IDLE),
            2 => Some(StateVariant::STATE_BUSY),
            5 => Some(StateVariant::STATE_DONE),
            7 => Some(StateVariant::STATE_ERROR),
            _ => None,
        };

        Ok(variant)
    }

    /// Returns the original HDL name of the current known variant.
    ///
    /// Unknown values return `None`.
    ///
    /// # Errors
    ///
    /// Returns an error if packed storage extraction fails.
    pub fn name(&self) -> std::result::Result<Option<&'static str>, ::vvm::PackedLayoutError> {
        Ok(self.variant()?.map(StateVariant::name))
    }

    /// Returns whether this value matches a declared HDL variant.
    ///
    /// # Errors
    ///
    /// Returns an error if packed storage extraction fails.
    pub fn is_known(&self) -> std::result::Result<bool, ::vvm::PackedLayoutError> {
        Ok(self.variant()?.is_some())
    }
}

impl Default for State {
    fn default() -> Self {
        Self::zero()
    }
}

impl From<StateVariant> for State {
    fn from(variant: StateVariant) -> Self {
        Self::from_variant(variant)
    }
}

#[allow(clippy::same_name_method)]
impl ::vvm::PackedValue for State {
    const WIDTH: usize = Self::WIDTH;
    const WORDS: usize = Self::WORDS;

    fn from_words_le(
        words: impl AsRef<[u32]>,
    ) -> std::result::Result<Self, ::vvm::InvalidBitVectorWordCount> {
        Self::from_words_le(words)
    }

    fn words_le(&self) -> &[u32] {
        self.words_le()
    }
}

impl From<::vvm::Bits<3>> for State {
    fn from(bits: ::vvm::Bits<3>) -> Self {
        Self::from_bits(bits)
    }
}

impl From<State> for ::vvm::Bits<3> {
    fn from(value: State) -> Self {
        value.into_bits()
    }
}

/// Declared HDL variants of [`StateOut`].
#[allow(non_camel_case_types)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum StateOutVariant {
    STATE_IDLE,
    STATE_BUSY,
    STATE_DONE,
    STATE_ERROR,
}

impl StateOutVariant {
    /// Returns the canonical raw HDL discriminant.
    #[must_use]
    pub const fn raw(self) -> u64 {
        match self {
            Self::STATE_IDLE => 0,
            Self::STATE_BUSY => 2,
            Self::STATE_DONE => 5,
            Self::STATE_ERROR => 7,
        }
    }

    /// Returns the original HDL variant name.
    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
            Self::STATE_IDLE => "STATE_IDLE",
            Self::STATE_BUSY => "STATE_BUSY",
            Self::STATE_DONE => "STATE_DONE",
            Self::STATE_ERROR => "STATE_ERROR",
        }
    }
}

/// Packed-enum value used by the `state_out` DUT port.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct StateOut {
    /// Canonical flattened packed storage.
    bits: ::vvm::Bits<3>,
}

#[allow(clippy::same_name_method)]
impl StateOut {
    /// Total packed width.
    pub const WIDTH: usize = 3;

    /// Number of canonical transfer words.
    pub const WORDS: usize = ::vvm::Bits::<3>::WORDS;

    /// Declared enum variants in HDL declaration order.
    pub const VARIANTS: &'static [::vvm::PackedEnumVariantLayout] = &[
        ::vvm::PackedEnumVariantLayout::new("STATE_IDLE", 0),
        ::vvm::PackedEnumVariantLayout::new("STATE_BUSY", 2),
        ::vvm::PackedEnumVariantLayout::new("STATE_DONE", 5),
        ::vvm::PackedEnumVariantLayout::new("STATE_ERROR", 7),
    ];

    /// Complete packed-enum layout.
    pub const LAYOUT: ::vvm::PackedEnumLayout =
        ::vvm::PackedEnumLayout::new("StateOut", Self::WIDTH, false, Self::VARIANTS);

    /// Constructs an all-zero packed-enum value.
    #[must_use]
    pub fn zero() -> Self {
        Self {
            bits: ::vvm::Bits::<3>::zero(),
        }
    }

    /// Wraps canonical packed bits.
    #[must_use]
    pub const fn from_bits(bits: ::vvm::Bits<3>) -> Self {
        Self {
            bits,
        }
    }

    /// Returns the underlying packed bits.
    #[must_use]
    pub const fn bits(&self) -> &::vvm::Bits<3> {
        &self.bits
    }

    /// Returns the packed width.
    #[must_use]
    pub const fn width() -> usize {
        Self::WIDTH
    }

    /// Returns the packed-enum layout.
    #[must_use]
    pub const fn layout() -> ::vvm::PackedEnumLayout {
        Self::LAYOUT
    }

    /// Returns declared HDL variants in declaration order.
    #[must_use]
    pub const fn variants() -> &'static [::vvm::PackedEnumVariantLayout] {
        Self::VARIANTS
    }

    /// Consumes the value and returns its packed bits.
    #[must_use]
    pub fn into_bits(self) -> ::vvm::Bits<3> {
        self.bits
    }

    /// Constructs the packed enum from canonical words.
    ///
    /// # Errors
    ///
    /// Returns an error when the word count does not match the packed width.
    pub fn from_words_le(
        words: impl AsRef<[u32]>,
    ) -> std::result::Result<Self, ::vvm::InvalidBitVectorWordCount> {
        ::vvm::Bits::<3>::from_words_le(words)
            .map(Self::from_bits)
    }

    /// Returns canonical least-significant-word-first words.
    #[must_use]
    pub fn words_le(&self) -> &[u32] {
        self.bits.words_le()
    }

    /// Constructs a packed-enum value from its raw bit pattern.
    ///
    /// Only the low [`Self::WIDTH`] bits are retained.
    #[must_use]
    pub fn from_raw(value: u64) -> Self {
        Self::from_bits(::vvm::Bits::<3>::from(value))
    }

    /// Returns the canonical raw enum bit pattern.
    ///
    /// # Errors
    ///
    /// Returns an error if the internal packed storage cannot be extracted.
    pub fn raw(&self) -> std::result::Result<u64, ::vvm::PackedLayoutError> {
        ::vvm::extract_unsigned(
            self.words_le(),
            Self::WIDTH,
            0,
            Self::WIDTH,
        )
    }

    /// Constructs a packed value from one declared HDL variant.
    #[must_use]
    pub fn from_variant(variant: StateOutVariant) -> Self {
        Self::from_raw(variant.raw())
    }

    /// Returns the declared variant matching this raw value.
    ///
    /// Unknown but valid HDL bit patterns return `None`.
    ///
    /// # Errors
    ///
    /// Returns an error if packed storage extraction fails.
    pub fn variant(&self) -> std::result::Result<Option<StateOutVariant>, ::vvm::PackedLayoutError> {
        let variant = match self.raw()? {
            0 => Some(StateOutVariant::STATE_IDLE),
            2 => Some(StateOutVariant::STATE_BUSY),
            5 => Some(StateOutVariant::STATE_DONE),
            7 => Some(StateOutVariant::STATE_ERROR),
            _ => None,
        };

        Ok(variant)
    }

    /// Returns the original HDL name of the current known variant.
    ///
    /// Unknown values return `None`.
    ///
    /// # Errors
    ///
    /// Returns an error if packed storage extraction fails.
    pub fn name(&self) -> std::result::Result<Option<&'static str>, ::vvm::PackedLayoutError> {
        Ok(self.variant()?.map(StateOutVariant::name))
    }

    /// Returns whether this value matches a declared HDL variant.
    ///
    /// # Errors
    ///
    /// Returns an error if packed storage extraction fails.
    pub fn is_known(&self) -> std::result::Result<bool, ::vvm::PackedLayoutError> {
        Ok(self.variant()?.is_some())
    }
}

impl Default for StateOut {
    fn default() -> Self {
        Self::zero()
    }
}

impl From<StateOutVariant> for StateOut {
    fn from(variant: StateOutVariant) -> Self {
        Self::from_variant(variant)
    }
}

#[allow(clippy::same_name_method)]
impl ::vvm::PackedValue for StateOut {
    const WIDTH: usize = Self::WIDTH;
    const WORDS: usize = Self::WORDS;

    fn from_words_le(
        words: impl AsRef<[u32]>,
    ) -> std::result::Result<Self, ::vvm::InvalidBitVectorWordCount> {
        Self::from_words_le(words)
    }

    fn words_le(&self) -> &[u32] {
        self.words_le()
    }
}

impl From<::vvm::Bits<3>> for StateOut {
    fn from(bits: ::vvm::Bits<3>) -> Self {
        Self::from_bits(bits)
    }
}

impl From<StateOut> for ::vvm::Bits<3> {
    fn from(value: StateOut) -> Self {
        value.into_bits()
    }
}

/// Declared HDL variants of [`SignedState`].
#[allow(non_camel_case_types)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SignedStateVariant {
    SIGNED_NEG,
    SIGNED_ZERO,
    SIGNED_POS,
}

impl SignedStateVariant {
    /// Returns the canonical raw HDL discriminant.
    #[must_use]
    pub const fn raw(self) -> u64 {
        match self {
            Self::SIGNED_NEG => 13,
            Self::SIGNED_ZERO => 0,
            Self::SIGNED_POS => 5,
        }
    }

    /// Returns the original HDL variant name.
    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
            Self::SIGNED_NEG => "SIGNED_NEG",
            Self::SIGNED_ZERO => "SIGNED_ZERO",
            Self::SIGNED_POS => "SIGNED_POS",
        }
    }
}

/// Packed-enum value used by the `signed_state` DUT port.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct SignedState {
    /// Canonical flattened packed storage.
    bits: ::vvm::SignedBits<4>,
}

#[allow(clippy::same_name_method)]
impl SignedState {
    /// Total packed width.
    pub const WIDTH: usize = 4;

    /// Number of canonical transfer words.
    pub const WORDS: usize = ::vvm::SignedBits::<4>::WORDS;

    /// Declared enum variants in HDL declaration order.
    pub const VARIANTS: &'static [::vvm::PackedEnumVariantLayout] = &[
        ::vvm::PackedEnumVariantLayout::new("SIGNED_NEG", 13),
        ::vvm::PackedEnumVariantLayout::new("SIGNED_ZERO", 0),
        ::vvm::PackedEnumVariantLayout::new("SIGNED_POS", 5),
    ];

    /// Complete packed-enum layout.
    pub const LAYOUT: ::vvm::PackedEnumLayout =
        ::vvm::PackedEnumLayout::new("SignedState", Self::WIDTH, true, Self::VARIANTS);

    /// Constructs an all-zero packed-enum value.
    #[must_use]
    pub fn zero() -> Self {
        Self {
            bits: ::vvm::SignedBits::<4>::zero(),
        }
    }

    /// Wraps canonical packed bits.
    #[must_use]
    pub const fn from_bits(bits: ::vvm::SignedBits<4>) -> Self {
        Self {
            bits,
        }
    }

    /// Returns the underlying packed bits.
    #[must_use]
    pub const fn bits(&self) -> &::vvm::SignedBits<4> {
        &self.bits
    }

    /// Returns the packed width.
    #[must_use]
    pub const fn width() -> usize {
        Self::WIDTH
    }

    /// Returns the packed-enum layout.
    #[must_use]
    pub const fn layout() -> ::vvm::PackedEnumLayout {
        Self::LAYOUT
    }

    /// Returns declared HDL variants in declaration order.
    #[must_use]
    pub const fn variants() -> &'static [::vvm::PackedEnumVariantLayout] {
        Self::VARIANTS
    }

    /// Consumes the value and returns its packed bits.
    #[must_use]
    pub fn into_bits(self) -> ::vvm::SignedBits<4> {
        self.bits
    }

    /// Constructs the packed enum from canonical words.
    ///
    /// # Errors
    ///
    /// Returns an error when the word count does not match the packed width.
    pub fn from_words_le(
        words: impl AsRef<[u32]>,
    ) -> std::result::Result<Self, ::vvm::InvalidBitVectorWordCount> {
        ::vvm::SignedBits::<4>::from_words_le(words)
            .map(Self::from_bits)
    }

    /// Returns canonical least-significant-word-first words.
    #[must_use]
    pub fn words_le(&self) -> &[u32] {
        self.bits.words_le()
    }

    /// Constructs a packed-enum value from its raw bit pattern.
    ///
    /// Only the low [`Self::WIDTH`] bits are retained.
    #[must_use]
    pub fn from_raw(value: u64) -> Self {
        let signed = i64::from_ne_bytes(value.to_ne_bytes());
        Self::from_bits(::vvm::SignedBits::<4>::from(signed))
    }

    /// Returns the canonical raw enum bit pattern.
    ///
    /// # Errors
    ///
    /// Returns an error if the internal packed storage cannot be extracted.
    pub fn raw(&self) -> std::result::Result<u64, ::vvm::PackedLayoutError> {
        ::vvm::extract_unsigned(
            self.words_le(),
            Self::WIDTH,
            0,
            Self::WIDTH,
        )
    }

    /// Constructs a packed value from one declared HDL variant.
    #[must_use]
    pub fn from_variant(variant: SignedStateVariant) -> Self {
        Self::from_raw(variant.raw())
    }

    /// Returns the declared variant matching this raw value.
    ///
    /// Unknown but valid HDL bit patterns return `None`.
    ///
    /// # Errors
    ///
    /// Returns an error if packed storage extraction fails.
    pub fn variant(&self) -> std::result::Result<Option<SignedStateVariant>, ::vvm::PackedLayoutError> {
        let variant = match self.raw()? {
            13 => Some(SignedStateVariant::SIGNED_NEG),
            0 => Some(SignedStateVariant::SIGNED_ZERO),
            5 => Some(SignedStateVariant::SIGNED_POS),
            _ => None,
        };

        Ok(variant)
    }

    /// Returns the original HDL name of the current known variant.
    ///
    /// Unknown values return `None`.
    ///
    /// # Errors
    ///
    /// Returns an error if packed storage extraction fails.
    pub fn name(&self) -> std::result::Result<Option<&'static str>, ::vvm::PackedLayoutError> {
        Ok(self.variant()?.map(SignedStateVariant::name))
    }

    /// Returns whether this value matches a declared HDL variant.
    ///
    /// # Errors
    ///
    /// Returns an error if packed storage extraction fails.
    pub fn is_known(&self) -> std::result::Result<bool, ::vvm::PackedLayoutError> {
        Ok(self.variant()?.is_some())
    }
}

impl Default for SignedState {
    fn default() -> Self {
        Self::zero()
    }
}

impl From<SignedStateVariant> for SignedState {
    fn from(variant: SignedStateVariant) -> Self {
        Self::from_variant(variant)
    }
}

#[allow(clippy::same_name_method)]
impl ::vvm::PackedValue for SignedState {
    const WIDTH: usize = Self::WIDTH;
    const WORDS: usize = Self::WORDS;

    fn from_words_le(
        words: impl AsRef<[u32]>,
    ) -> std::result::Result<Self, ::vvm::InvalidBitVectorWordCount> {
        Self::from_words_le(words)
    }

    fn words_le(&self) -> &[u32] {
        self.words_le()
    }
}

impl From<::vvm::SignedBits<4>> for SignedState {
    fn from(bits: ::vvm::SignedBits<4>) -> Self {
        Self::from_bits(bits)
    }
}

impl From<SignedState> for ::vvm::SignedBits<4> {
    fn from(value: SignedState) -> Self {
        value.into_bits()
    }
}

/// Declared HDL variants of [`SignedStateOut`].
#[allow(non_camel_case_types)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SignedStateOutVariant {
    SIGNED_NEG,
    SIGNED_ZERO,
    SIGNED_POS,
}

impl SignedStateOutVariant {
    /// Returns the canonical raw HDL discriminant.
    #[must_use]
    pub const fn raw(self) -> u64 {
        match self {
            Self::SIGNED_NEG => 13,
            Self::SIGNED_ZERO => 0,
            Self::SIGNED_POS => 5,
        }
    }

    /// Returns the original HDL variant name.
    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
            Self::SIGNED_NEG => "SIGNED_NEG",
            Self::SIGNED_ZERO => "SIGNED_ZERO",
            Self::SIGNED_POS => "SIGNED_POS",
        }
    }
}

/// Packed-enum value used by the `signed_state_out` DUT port.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct SignedStateOut {
    /// Canonical flattened packed storage.
    bits: ::vvm::SignedBits<4>,
}

#[allow(clippy::same_name_method)]
impl SignedStateOut {
    /// Total packed width.
    pub const WIDTH: usize = 4;

    /// Number of canonical transfer words.
    pub const WORDS: usize = ::vvm::SignedBits::<4>::WORDS;

    /// Declared enum variants in HDL declaration order.
    pub const VARIANTS: &'static [::vvm::PackedEnumVariantLayout] = &[
        ::vvm::PackedEnumVariantLayout::new("SIGNED_NEG", 13),
        ::vvm::PackedEnumVariantLayout::new("SIGNED_ZERO", 0),
        ::vvm::PackedEnumVariantLayout::new("SIGNED_POS", 5),
    ];

    /// Complete packed-enum layout.
    pub const LAYOUT: ::vvm::PackedEnumLayout =
        ::vvm::PackedEnumLayout::new("SignedStateOut", Self::WIDTH, true, Self::VARIANTS);

    /// Constructs an all-zero packed-enum value.
    #[must_use]
    pub fn zero() -> Self {
        Self {
            bits: ::vvm::SignedBits::<4>::zero(),
        }
    }

    /// Wraps canonical packed bits.
    #[must_use]
    pub const fn from_bits(bits: ::vvm::SignedBits<4>) -> Self {
        Self {
            bits,
        }
    }

    /// Returns the underlying packed bits.
    #[must_use]
    pub const fn bits(&self) -> &::vvm::SignedBits<4> {
        &self.bits
    }

    /// Returns the packed width.
    #[must_use]
    pub const fn width() -> usize {
        Self::WIDTH
    }

    /// Returns the packed-enum layout.
    #[must_use]
    pub const fn layout() -> ::vvm::PackedEnumLayout {
        Self::LAYOUT
    }

    /// Returns declared HDL variants in declaration order.
    #[must_use]
    pub const fn variants() -> &'static [::vvm::PackedEnumVariantLayout] {
        Self::VARIANTS
    }

    /// Consumes the value and returns its packed bits.
    #[must_use]
    pub fn into_bits(self) -> ::vvm::SignedBits<4> {
        self.bits
    }

    /// Constructs the packed enum from canonical words.
    ///
    /// # Errors
    ///
    /// Returns an error when the word count does not match the packed width.
    pub fn from_words_le(
        words: impl AsRef<[u32]>,
    ) -> std::result::Result<Self, ::vvm::InvalidBitVectorWordCount> {
        ::vvm::SignedBits::<4>::from_words_le(words)
            .map(Self::from_bits)
    }

    /// Returns canonical least-significant-word-first words.
    #[must_use]
    pub fn words_le(&self) -> &[u32] {
        self.bits.words_le()
    }

    /// Constructs a packed-enum value from its raw bit pattern.
    ///
    /// Only the low [`Self::WIDTH`] bits are retained.
    #[must_use]
    pub fn from_raw(value: u64) -> Self {
        let signed = i64::from_ne_bytes(value.to_ne_bytes());
        Self::from_bits(::vvm::SignedBits::<4>::from(signed))
    }

    /// Returns the canonical raw enum bit pattern.
    ///
    /// # Errors
    ///
    /// Returns an error if the internal packed storage cannot be extracted.
    pub fn raw(&self) -> std::result::Result<u64, ::vvm::PackedLayoutError> {
        ::vvm::extract_unsigned(
            self.words_le(),
            Self::WIDTH,
            0,
            Self::WIDTH,
        )
    }

    /// Constructs a packed value from one declared HDL variant.
    #[must_use]
    pub fn from_variant(variant: SignedStateOutVariant) -> Self {
        Self::from_raw(variant.raw())
    }

    /// Returns the declared variant matching this raw value.
    ///
    /// Unknown but valid HDL bit patterns return `None`.
    ///
    /// # Errors
    ///
    /// Returns an error if packed storage extraction fails.
    pub fn variant(&self) -> std::result::Result<Option<SignedStateOutVariant>, ::vvm::PackedLayoutError> {
        let variant = match self.raw()? {
            13 => Some(SignedStateOutVariant::SIGNED_NEG),
            0 => Some(SignedStateOutVariant::SIGNED_ZERO),
            5 => Some(SignedStateOutVariant::SIGNED_POS),
            _ => None,
        };

        Ok(variant)
    }

    /// Returns the original HDL name of the current known variant.
    ///
    /// Unknown values return `None`.
    ///
    /// # Errors
    ///
    /// Returns an error if packed storage extraction fails.
    pub fn name(&self) -> std::result::Result<Option<&'static str>, ::vvm::PackedLayoutError> {
        Ok(self.variant()?.map(SignedStateOutVariant::name))
    }

    /// Returns whether this value matches a declared HDL variant.
    ///
    /// # Errors
    ///
    /// Returns an error if packed storage extraction fails.
    pub fn is_known(&self) -> std::result::Result<bool, ::vvm::PackedLayoutError> {
        Ok(self.variant()?.is_some())
    }
}

impl Default for SignedStateOut {
    fn default() -> Self {
        Self::zero()
    }
}

impl From<SignedStateOutVariant> for SignedStateOut {
    fn from(variant: SignedStateOutVariant) -> Self {
        Self::from_variant(variant)
    }
}

#[allow(clippy::same_name_method)]
impl ::vvm::PackedValue for SignedStateOut {
    const WIDTH: usize = Self::WIDTH;
    const WORDS: usize = Self::WORDS;

    fn from_words_le(
        words: impl AsRef<[u32]>,
    ) -> std::result::Result<Self, ::vvm::InvalidBitVectorWordCount> {
        Self::from_words_le(words)
    }

    fn words_le(&self) -> &[u32] {
        self.words_le()
    }
}

impl From<::vvm::SignedBits<4>> for SignedStateOut {
    fn from(bits: ::vvm::SignedBits<4>) -> Self {
        Self::from_bits(bits)
    }
}

impl From<SignedStateOut> for ::vvm::SignedBits<4> {
    fn from(value: SignedStateOut) -> Self {
        value.into_bits()
    }
}

/// Error returned by generated DUT operations.
#[allow(dead_code)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PackedEnumPortsError {
    /// The native Verilated model could not be constructed.
    ConstructionFailed,

    /// The operation requires a DUT that has not been finished.
    Finished,

    /// The internal native adapter is unexpectedly unavailable.
    AdapterUnavailable,

    /// Simulation time would overflow.
    TimeOverflow,

    /// A generated packed-aggregate layout conversion failed.
    PackedLayoutFailed,
}

impl std::fmt::Display for PackedEnumPortsError {
    fn fmt(
        &self,
        formatter: &mut std::fmt::Formatter<'_>,
    ) -> std::fmt::Result {
        let message = match *self {
            Self::ConstructionFailed => "failed to construct the Verilated packed_enum_ports model",
            Self::Finished => "the packed_enum_ports model has already been finished",
            Self::AdapterUnavailable => "the packed_enum_ports native adapter is unexpectedly unavailable",
            Self::TimeOverflow => "advancing packed_enum_ports simulation time would overflow",
            Self::PackedLayoutFailed => {"the generated packed-aggregate layout conversion failed"},
        };

        formatter.write_str(message)
    }
}

impl std::error::Error for PackedEnumPortsError {}

/// Result type returned by generated DUT operations.
pub type Result<T> = std::result::Result<T, PackedEnumPortsError>;

/// Safe Rust wrapper for the `packed_enum_ports` Verilated DUT.
pub struct PackedEnumPorts {
    /// Opaque ownership of the generated C++ adapter.
    inner: ::vvm::__private::cxx::UniquePtr<ffi::PackedEnumPorts>,

    /// Tracks whether finalisation has already completed.
    finished: bool,

    /// Current logical simulation time.
    time: ::vvm::SimulationTime,
}

#[allow(dead_code)]
impl PackedEnumPorts {
    /// Constructs the Verilated DUT.
    ///
    /// # Errors
    ///
    /// Returns an error when the native adapter cannot be constructed.
    pub fn new() -> Result<Self> {
        let inner = ffi::create_packed_enum_ports();

        Self::from_inner(inner)
    }

    /// Constructs Verilated DUT from an internal [`::vvm::__private::cxx::UniquePtr`].
    fn from_inner(inner: ::vvm::__private::cxx::UniquePtr<ffi::PackedEnumPorts>) -> Result<Self> {
        if inner.is_null() {
            return Err(PackedEnumPortsError::ConstructionFailed);
        }

        Ok(Self {
            inner,
            finished: false,
            time: ::vvm::SimulationTime::ZERO,
        })
    }

    /// Returns whether the DUT has been finalised.
    #[must_use]
    pub const fn is_finished(&self) -> bool {
        self.finished
    }

    /// Evaluates the current DUT state.
    ///
    /// # Errors
    ///
    /// Returns an error if the DUT has already been finished.
    pub fn eval(&mut self) -> Result<()> {
        self.ensure_running()?;
        self.inner_mut()?.eval();

        Ok(())
    }

    /// Finalises the DUT exactly once.
    ///
    /// Calling this method repeatedly is safe.
    ///
    /// # Errors
    ///
    /// Returns an error if the native adapter is unexpectedly unavailable.
    pub fn finish(&mut self) -> Result<()> {
        if self.finished {
            return Ok(());
        }

        self.inner_mut()?.finish();
        self.finished = true;

        Ok(())
    }
    /// Returns the current simulation time.
    #[must_use]
    const fn simulation_time_value(
        &self,
    ) -> ::vvm::SimulationTime {
        self.time
    }
    /// Advances the simulation time without evaluating the DUT.
    ///
    /// # Errors
    ///
    /// Returns an error if the DUT is finished, the adapter is unavailable, or
    /// the resulting time would overflow.
    fn advance_time_inner(
        &mut self,
        delta: ::vvm::TimeStep,
    ) -> Result<()> {
        self.ensure_running()?;
        let Some(next_time) =
            self.time.checked_add(delta)
        else {
            return Err(PackedEnumPortsError::TimeOverflow);
        };
        let advanced = self
            .inner_mut()?
            .advance_time(delta.ticks());
        if !advanced {
            return Err(PackedEnumPortsError::TimeOverflow);
        }
        self.time = next_time;
        Ok(())
    }

    /// Drives the `clk` DUT input.
    ///
    /// The value may be supplied by value or by reference.
    ///
    /// # Errors
    ///
    /// Returns an error if the DUT has already been finished.
    #[allow(clippy::needless_pass_by_value)]
    pub fn set_clk(
        &mut self,
        value: impl ::core::borrow::Borrow<bool>,
    ) -> Result<()> {
        self.ensure_running()?;

        let value: bool =
            *::core::borrow::Borrow::borrow(&value);

        self.inner_mut()?.set_clk(value);

        Ok(())
    }

    /// Drives the `state` DUT input.
    ///
    /// The value may be supplied by value or by reference.
    ///
    /// # Errors
    ///
    /// Returns an error if the DUT has already been finished, a generated
    /// packed-aggregate layout conversion fails, or a native wide transfer is rejected.
    #[allow(clippy::needless_pass_by_value)]
    pub fn set_state(
        &mut self,
        value: impl ::core::borrow::Borrow<State>,
    ) -> Result<()> {
        self.ensure_running()?;

        let value =
            ::core::borrow::Borrow::borrow(&value);

        let raw = ::vvm::extract_unsigned(
            value.words_le(),
            State::WIDTH,
            0,
            State::WIDTH,
        )
        .map_err(|_error| PackedEnumPortsError::PackedLayoutFailed)?;

        let raw: u8 = u8::try_from(raw)
            .map_err(|_error| PackedEnumPortsError::PackedLayoutFailed)?;

        self.inner_mut()?.set_state(raw);

        Ok(())
    }

    /// Samples the `state_out` DUT output.
    ///
    /// # Errors
    ///
    /// Returns an error if the DUT has already been finished, a generated
    /// packed-aggregate layout conversion fails, or a native wide transfer is rejected.
    pub fn state_out(&self) -> Result<StateOut> {
        self.ensure_running()?;

        let raw = self.inner_ref()?.state_out();

        let bits = ::vvm::Bits::<3>::from(
            u64::from(raw),
        );

        Ok(StateOut::from_bits(bits))
    }

    /// Samples the `state_raw_out` DUT output.
    ///
    /// # Errors
    ///
    /// Returns an error if the DUT has already been finished.
    pub fn state_raw_out(&self) -> Result<u8> {
        self.ensure_running()?;

        Ok(self.inner_ref()?.state_raw_out())
    }

    /// Drives the `signed_state` DUT input.
    ///
    /// The value may be supplied by value or by reference.
    ///
    /// # Errors
    ///
    /// Returns an error if the DUT has already been finished, a generated
    /// packed-aggregate layout conversion fails, or a native wide transfer is rejected.
    #[allow(clippy::needless_pass_by_value)]
    pub fn set_signed_state(
        &mut self,
        value: impl ::core::borrow::Borrow<SignedState>,
    ) -> Result<()> {
        self.ensure_running()?;

        let value =
            ::core::borrow::Borrow::borrow(&value);

        let raw = ::vvm::extract_signed(
            value.words_le(),
            SignedState::WIDTH,
            0,
            SignedState::WIDTH,
        )
        .map_err(|_error| PackedEnumPortsError::PackedLayoutFailed)?;

        let raw: i8 = i8::try_from(raw)
            .map_err(|_error| PackedEnumPortsError::PackedLayoutFailed)?;

        self.inner_mut()?.set_signed_state(raw);

        Ok(())
    }

    /// Samples the `signed_state_out` DUT output.
    ///
    /// # Errors
    ///
    /// Returns an error if the DUT has already been finished, a generated
    /// packed-aggregate layout conversion fails, or a native wide transfer is rejected.
    pub fn signed_state_out(&self) -> Result<SignedStateOut> {
        self.ensure_running()?;

        let raw = self.inner_ref()?.signed_state_out();

        let bits = ::vvm::SignedBits::<4>::from(
            i64::from(raw),
        );

        Ok(SignedStateOut::from_bits(bits))
    }

    /// Samples the `signed_state_raw_out` DUT output.
    ///
    /// # Errors
    ///
    /// Returns an error if the DUT has already been finished.
    pub fn signed_state_raw_out(&self) -> Result<i8> {
        self.ensure_running()?;

        Ok(self.inner_ref()?.signed_state_raw_out())
    }

    /// Ensures that operations may still access the DUT.
    const fn ensure_running(&self) -> Result<()> {
        if self.finished {
            return Err(PackedEnumPortsError::Finished);
        }

        Ok(())
    }

    /// Returns an immutable reference to the native adapter.
    fn inner_ref(&self) -> Result<&ffi::PackedEnumPorts> {
        self.inner.as_ref().ok_or(
            PackedEnumPortsError::AdapterUnavailable,
        )
    }

    /// Returns a pinned mutable reference to the native adapter.
    fn inner_mut(&mut self) -> Result<std::pin::Pin<&mut ffi::PackedEnumPorts>> {
        self.inner.as_mut().ok_or(
            PackedEnumPortsError::AdapterUnavailable,
        )
    }
}

impl std::fmt::Debug for PackedEnumPorts {
    fn fmt(
        &self,
        formatter: &mut std::fmt::Formatter<'_>,
    ) -> std::fmt::Result {
        formatter.debug_struct("PackedEnumPorts")
            .field("finished", &self.finished)
            .field("time", &self.time)
            .finish_non_exhaustive()
    }
}

impl ::vvm::Dut for PackedEnumPorts {
    type Error = PackedEnumPortsError;

    fn evaluate(&mut self) -> Result<()> {
        Self::eval(self)
    }

    fn finalize(&mut self) -> Result<()> {
        Self::finish(self)
    }
    fn simulation_time(
        &self,
    ) -> ::vvm::SimulationTime {
        Self::simulation_time_value(self)
    }
    fn advance_time(
        &mut self,
        delta: ::vvm::TimeStep,
    ) -> Result<()> {
        Self::advance_time_inner(self, delta)
    }
}

impl Drop for PackedEnumPorts {
    fn drop(&mut self) {
        if self.finished {
            return;
        }

        if let Some(inner) = self.inner.as_mut() {
            inner.finish();
        }

        self.finished = true;
    }
}
