// @generated by vvm-build. Do not edit.

#pragma once

#include <cstdint>
#include <memory>

namespace vvm::packed_enum_ports {

class PackedEnumPorts final {
public:
    PackedEnumPorts();
    ~PackedEnumPorts() noexcept;

    PackedEnumPorts(const PackedEnumPorts&) = delete;
    PackedEnumPorts& operator=(const PackedEnumPorts&) = delete;

    PackedEnumPorts(PackedEnumPorts&&) = delete;
    PackedEnumPorts& operator=(PackedEnumPorts&&) = delete;

    void eval() noexcept;
    void finish() noexcept;
    [[nodiscard]]
    bool advance_time(std::uint64_t delta) noexcept;

    void set_clk(bool value) noexcept;
    void set_state(std::uint8_t value) noexcept;
    [[nodiscard]] std::uint8_t state_out() const noexcept;
    [[nodiscard]] std::uint8_t state_raw_out() const noexcept;
    void set_signed_state(std::int8_t value) noexcept;
    [[nodiscard]] std::int8_t signed_state_out() const noexcept;
    [[nodiscard]] std::int8_t signed_state_raw_out() const noexcept;

private:
    class Impl;
    std::unique_ptr<Impl> impl_;
};

[[nodiscard]] std::unique_ptr<PackedEnumPorts> create_packed_enum_ports() noexcept;

} // namespace vvm::packed_enum_ports
