// @generated by vvm-build. Do not edit.

#include "packed_enum_ports.hpp"

#include "Vpacked_enum_ports.h"
#include "verilated.h"

#include <cstdint>
#include <memory>
#include <type_traits>
#include <limits>

namespace vvm::packed_enum_ports {

class PackedEnumPorts::Impl final {
public:
    Impl()
        : context{std::make_unique<VerilatedContext>()},
          model{std::make_unique<Vpacked_enum_ports>(context.get())} {
        {
            using RawType = std::decay_t<decltype(model->clk())>;
            RawType raw_value{0};
            model->clk(raw_value);
        }
        {
            using RawType = std::decay_t<decltype(model->state())>;
            RawType raw_value{0};
            model->state(raw_value);
        }
        {
            using RawType = std::decay_t<decltype(model->signed_state())>;
            RawType raw_value{0};
            model->signed_state(raw_value);
        }
    }

    template <typename Signed, std::uint32_t Width, typename Raw>
    [[nodiscard]]
    static constexpr Signed sign_extend(
        const Raw raw
    ) noexcept {
        static_assert(std::is_integral_v<Signed>);
        static_assert(std::is_signed_v<Signed>);
        static_assert(std::is_integral_v<Raw>);

        using Unsigned = std::make_unsigned_t<Signed>;

        constexpr auto storage_width =
            static_cast<std::uint32_t>(
                std::numeric_limits<Unsigned>::digits
            );

        static_assert(Width > 0);
        static_assert(Width <= storage_width);

        Unsigned mask{
            std::numeric_limits<Unsigned>::max()
        };

        if constexpr (Width < storage_width) {
            mask = static_cast<Unsigned>(
                static_cast<Unsigned>(
                    Unsigned{1} << Width
                ) - Unsigned{1}
            );
        }

        const auto value = static_cast<Unsigned>(
            static_cast<Unsigned>(raw) & mask
        );

        constexpr auto sign_bit =
            static_cast<Unsigned>(
                Unsigned{1} << (Width - 1U)
            );

        if ((value & sign_bit) == Unsigned{0}) {
            return static_cast<Signed>(value);
        }

        const auto magnitude =
            static_cast<Unsigned>(
                static_cast<Unsigned>(
                    static_cast<Unsigned>(~value) & mask
                ) + Unsigned{1}
            );

        if (
            magnitude
            > static_cast<Unsigned>(
                std::numeric_limits<Signed>::max()
            )
        ) {
            return std::numeric_limits<Signed>::min();
        }

        return static_cast<Signed>(
            -static_cast<Signed>(magnitude)
        );
    }

    std::unique_ptr<VerilatedContext> context;
    std::unique_ptr<Vpacked_enum_ports> model;
    bool finished{false};
};

PackedEnumPorts::PackedEnumPorts()
    : impl_{std::make_unique<Impl>()} {}

PackedEnumPorts::~PackedEnumPorts() noexcept {
    finish();
}

void PackedEnumPorts::eval() noexcept {
    if (impl_->finished) {
        return;
    }

    impl_->model->eval();
}

void PackedEnumPorts::finish() noexcept {
    if (impl_->finished) {
        return;
    }

    impl_->model->final();

    impl_->finished = true;
}

void PackedEnumPorts::set_clk(const bool value) noexcept {
    using RawType = std::decay_t<decltype(impl_->model->clk())>;

    RawType raw_value{static_cast<RawType>(value)};
    impl_->model->clk(raw_value);
}

void PackedEnumPorts::set_state(const std::uint8_t value) noexcept {
    using RawType = std::decay_t<decltype(impl_->model->state())>;

    RawType raw_value{static_cast<RawType>(value & static_cast<std::uint8_t>(0x7ULL))};
    impl_->model->state(raw_value);
}

std::uint8_t PackedEnumPorts::state_out() const noexcept {
    return static_cast<std::uint8_t>(impl_->model->state_out() & static_cast<std::uint8_t>(0x7ULL));
}

std::uint8_t PackedEnumPorts::state_raw_out() const noexcept {
    return static_cast<std::uint8_t>(impl_->model->state_raw_out() & static_cast<std::uint8_t>(0x7ULL));
}

void PackedEnumPorts::set_signed_state(const std::int8_t value) noexcept {
    using RawType = std::decay_t<decltype(impl_->model->signed_state())>;
    using UnsignedType = std::uint8_t;

    const auto bits = static_cast<UnsignedType>(value);
    RawType raw_value{static_cast<RawType>(bits & static_cast<std::uint8_t>(0xFULL))};
    impl_->model->signed_state(raw_value);
}

std::int8_t PackedEnumPorts::signed_state_out() const noexcept {
    return Impl::sign_extend<std::int8_t, 4>(
        impl_->model->signed_state_out()
    );
}

std::int8_t PackedEnumPorts::signed_state_raw_out() const noexcept {
    return Impl::sign_extend<std::int8_t, 4>(
        impl_->model->signed_state_raw_out()
    );
}

bool PackedEnumPorts::advance_time(
    const std::uint64_t delta
) noexcept {
    const auto current = impl_->context->time();

    if (delta > std::numeric_limits<std::uint64_t>::max() - current) {
        return false;
    }

    impl_->context->timeInc(delta);

    return true;
}

std::unique_ptr<PackedEnumPorts> create_packed_enum_ports() noexcept {
    try {
        return std::make_unique<PackedEnumPorts>();
    } catch (...) {
        return nullptr;
    }
}

} // namespace vvm::packed_enum_ports
