// @generated by vvm-build. Do not edit.

include!(concat!(
    env!("OUT_DIR"),
    "/vvm/counter/generated/bridge.rs"
));

/// Result type returned by generated DUT operations.
pub type Result<T> = std::result::Result<T, &'static str>;

/// Safe Rust wrapper for the `counter` Verilated DUT.
pub struct Counter {
    /// Opaque ownership of the generated C++ adapter.
    inner: cxx::UniquePtr<ffi::Counter>,

    /// Tracks whether finalisation has already been forwarded.
    finished: bool,
}

impl Counter {
    /// Constructs the Verilated DUT.
    ///
    /// # Errors
    ///
    /// Returns an error when the generated C++ adapter cannot be constructed.
    pub fn new() -> Result<Self> {
        let inner = ffi::create_counter();

        if inner.is_null() {
            return Err("failed to construct the Verilated counter model");
        }

        Ok(Self {
            inner,
            finished: false,
        })
    }

    /// Evaluates the current DUT state.
    pub fn eval(&mut self) {
        self.inner_mut().eval();
    }

    /// Finalises the DUT exactly once.
    pub fn finish(&mut self) {
        if self.finished {
            return;
        }

        self.inner_mut().finish();
        self.finished = true;
    }

    /// Drives the `clk` DUT input.
    pub fn set_clk(&mut self, value: bool) {
        self.inner_mut().set_clk(value);
    }

    /// Drives the `reset_n` DUT input.
    pub fn set_reset_n(&mut self, value: bool) {
        self.inner_mut().set_reset_n(value);
    }

    /// Drives the `enable` DUT input.
    pub fn set_enable(&mut self, value: bool) {
        self.inner_mut().set_enable(value);
    }

    /// Samples the `count` DUT output.
    ///
    /// # Errors
    ///
    /// Returns an error if the internal C++ adapter pointer is unexpectedly null.
    pub fn count(&self) -> Result<u8> {
        self.inner
            .as_ref()
            .map(ffi::Counter::count)
            .ok_or("counter model unexpectedly became null")
    }

    /// Returns a pinned mutable reference to the generated C++ adapter.
    fn inner_mut(&mut self) -> std::pin::Pin<&mut ffi::Counter> {
        self.inner.pin_mut()
    }
}

impl Drop for Counter {
    fn drop(&mut self) {
        self.finish();
    }
}
