// @generated by vvm-build. Do not edit.

include!(concat!(
    env!("OUT_DIR"),
    "/vvm/counter/generated/bridge.rs"
));

/// Error returned by generated DUT operations.
#[allow(dead_code)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CounterError {
    /// The native Verilated model could not be constructed.
    ConstructionFailed,

    /// The operation requires a DUT that has not been finished.
    Finished,

    /// The internal native adapter is unexpectedly unavailable.
    AdapterUnavailable,

    /// Simulation time would overflow.
    TimeOverflow,
}

impl std::fmt::Display for CounterError {
    fn fmt(
        &self,
        formatter: &mut std::fmt::Formatter<'_>,
    ) -> std::fmt::Result {
        let message = match *self {
            Self::ConstructionFailed => "failed to construct the Verilated counter model",
            Self::Finished => "the counter model has already been finished",
            Self::AdapterUnavailable => "the counter native adapter is unexpectedly unavailable",
            Self::TimeOverflow => "advancing counter simulation time would overflow"
        };

        formatter.write_str(message)
    }
}

impl std::error::Error for CounterError {}

/// Result type returned by generated DUT operations.
pub type Result<T> = std::result::Result<T, CounterError>;

/// Safe Rust wrapper for the `counter` Verilated DUT.
pub struct Counter {
    /// Opaque ownership of the generated C++ adapter.
    inner: ::vvm::__private::cxx::UniquePtr<ffi::Counter>,

    /// Tracks whether finalisation has already completed.
    finished: bool,

    /// Current logical simulation time.
    time: ::vvm::SimulationTime,
}

#[allow(dead_code)]
impl Counter {
    /// Constructs the Verilated DUT.
    ///
    /// # Errors
    ///
    /// Returns an error when the native adapter cannot be constructed.
    pub fn new() -> Result<Self> {
        let inner = ffi::create_counter();

        Self::from_inner(inner)
    }

    /// Constructs Verilated DUT from an internal [`::vvm::__private::cxx::UniquePtr`].
    fn from_inner(inner: ::vvm::__private::cxx::UniquePtr<ffi::Counter>) -> Result<Self> {
        if inner.is_null() {
            return Err(CounterError::ConstructionFailed);
        }

        Ok(Self {
            inner,
            finished: false,
            time: ::vvm::SimulationTime::ZERO,
        })
    }

    /// Returns whether the DUT has been finalised.
    #[must_use]
    pub const fn is_finished(&self) -> bool {
        self.finished
    }

    /// Evaluates the current DUT state.
    ///
    /// # Errors
    ///
    /// Returns an error if the DUT has already been finished.
    pub fn eval(&mut self) -> Result<()> {
        self.ensure_running()?;
        self.inner_mut()?.eval();

        Ok(())
    }

    /// Finalises the DUT exactly once.
    ///
    /// Calling this method repeatedly is safe.
    ///
    /// # Errors
    ///
    /// Returns an error if the native adapter is unexpectedly unavailable.
    pub fn finish(&mut self) -> Result<()> {
        if self.finished {
            return Ok(());
        }

        self.inner_mut()?.finish();
        self.finished = true;

        Ok(())
    }
    /// Returns the current simulation time.
    #[must_use]
    const fn simulation_time_value(
        &self,
    ) -> ::vvm::SimulationTime {
        self.time
    }
    /// Advances the simulation time without evaluating the DUT.
    ///
    /// # Errors
    ///
    /// Returns an error if the DUT is finished, the adapter is unavailable, or
    /// the resulting time would overflow.
    fn advance_time_inner(
        &mut self,
        delta: ::vvm::TimeStep,
    ) -> Result<()> {
        self.ensure_running()?;
        let Some(next_time) =
            self.time.checked_add(delta)
        else {
            return Err(CounterError::TimeOverflow);
        };
        let advanced = self
            .inner_mut()?
            .advance_time(delta.ticks());
        if !advanced {
            return Err(CounterError::TimeOverflow);
        }
        self.time = next_time;
        Ok(())
    }

    /// Drives the `clk` DUT input.
    ///
    /// # Errors
    ///
    /// Returns an error if the DUT has already been finished.
    pub fn set_clk(&mut self, value: bool) -> Result<()> {
        self.ensure_running()?;
        self.inner_mut()?.set_clk(value);

        Ok(())
    }

    /// Drives the `reset_n` DUT input.
    ///
    /// # Errors
    ///
    /// Returns an error if the DUT has already been finished.
    pub fn set_reset_n(&mut self, value: bool) -> Result<()> {
        self.ensure_running()?;
        self.inner_mut()?.set_reset_n(value);

        Ok(())
    }

    /// Drives the `enable` DUT input.
    ///
    /// # Errors
    ///
    /// Returns an error if the DUT has already been finished.
    pub fn set_enable(&mut self, value: bool) -> Result<()> {
        self.ensure_running()?;
        self.inner_mut()?.set_enable(value);

        Ok(())
    }

    /// Samples the `count` DUT output.
    ///
    /// # Errors
    ///
    /// Returns an error if the DUT has already been finished.
    pub fn count(&self) -> Result<u8> {
        self.ensure_running()?;

        Ok(self.inner_ref()?.count())
    }

    /// Ensures that operations may still access the DUT.
    const fn ensure_running(&self) -> Result<()> {
        if self.finished {
            return Err(CounterError::Finished);
        }

        Ok(())
    }

    /// Returns an immutable reference to the native adapter.
    fn inner_ref(&self) -> Result<&ffi::Counter> {
        self.inner.as_ref().ok_or(
            CounterError::AdapterUnavailable,
        )
    }

    /// Returns a pinned mutable reference to the native adapter.
    fn inner_mut(&mut self) -> Result<std::pin::Pin<&mut ffi::Counter>> {
        self.inner.as_mut().ok_or(
            CounterError::AdapterUnavailable,
        )
    }
}

impl std::fmt::Debug for Counter {
    fn fmt(
        &self,
        formatter: &mut std::fmt::Formatter<'_>,
    ) -> std::fmt::Result {
        formatter.debug_struct("Counter")
            .field("finished", &self.finished)
            .field("time", &self.time)
            .finish_non_exhaustive()
    }
}

impl ::vvm::Dut for Counter {
    type Error = CounterError;

    fn evaluate(&mut self) -> Result<()> {
        Self::eval(self)
    }

    fn finalize(&mut self) -> Result<()> {
        Self::finish(self)
    }
    fn simulation_time(
        &self,
    ) -> ::vvm::SimulationTime {
        Self::simulation_time_value(self)
    }
    fn advance_time(
        &mut self,
        delta: ::vvm::TimeStep,
    ) -> Result<()> {
        Self::advance_time_inner(self, delta)
    }
}

impl Drop for Counter {
    fn drop(&mut self) {
        if self.finished {
            return;
        }

        if let Some(inner) = self.inner.as_mut() {
            inner.finish();
        }

        self.finished = true;
    }
}
