[package]
name = "vvm-macros"
version.workspace       = true
authors.workspace       = true
edition.workspace       = true
rust-version.workspace  = true
homepage.workspace      = true
repository.workspace    = true
license.workspace       = true
keywords.workspace      = true
categories.workspace    = true
description             = "VVM procedural macros and helper attributes"
readme                  = "README.md"
documentation           = "https://byacrates.gitlab.io/vvm-rs/api/vvm_macros/"

[lib]
proc-macro = true
bench = false

[lints]
workspace = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn = { workspace = true, features = ["full"] }

[package.metadata.cargo-udeps.ignore]
normal = [
    "vvm",
    "vvm-build",
    "vvm-core",
    "vvm-macros",
]
development = ["criterion"]
