[package]
name = "vvm-example-counter"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false
build = "build.rs"
description = "Minimal counter example for the first VVM integration slice"

[lints]
workspace = true

[dependencies]
cxx.workspace = true

[build-dependencies]
vvm-build.workspace = true
