//! Behavioral UART transmitter verified by reconstructing timed output events.

// The timing-enabled wrapper is generated by the example's build script.
vvm::include_dut!(timed_uart);

#[doc(hidden)]
pub mod benchmark;

#[cfg(test)]
/// Timed UART protocol reconstruction and coverage tests.
mod tests {
    use std::path::Path;

    use thiserror::Error;
    use vvm::coverage::{
        Bin, CoverageGroup, CoverageGroupInstance, CoverageGroupVisitor, CoverageItemRef,
        Coverpoint, Cross2,
    };
    use vvm::dut::Dut;
    use vvm::random::{RandomContext, ReplayToken, Seed};
    use vvm::test::TestContext;
    use vvm::testbench::TestResult;
    use vvm::timing::{SchedulerError, SimulationTime, TimingScheduler};

    use crate::timed_uart::{TimedUart, TimedUartError};

    /// Errors returned while driving or decoding timed UART frames.
    #[derive(Debug, Error)]
    enum Error {
        #[error(transparent)]
        Dut(#[from] TimedUartError),

        #[error(transparent)]
        Timing(#[from] SchedulerError<TimedUartError>),

        #[error(transparent)]
        Io(#[from] std::io::Error),

        #[error(transparent)]
        CoverageBuild(#[from] vvm::coverage::BuildError),

        #[error(transparent)]
        CoverageGroup(#[from] vvm::coverage::GroupError),

        #[error(transparent)]
        CoverageSample(#[from] vvm::coverage::SampleError),

        #[error(transparent)]
        CrossBuild(#[from] vvm::coverage::CrossBuildError),

        #[error(transparent)]
        CrossSample(#[from] vvm::coverage::CrossSampleError),

        #[error(transparent)]
        CoverageSession(#[from] vvm::coverage::session::SessionError),
    }

    /// Result type used by UART helpers and tests.
    type Result<T> = std::result::Result<T, Error>;

    /// Inputs latched by the behavioral model before its initialization evaluation.
    #[derive(Clone, Copy, Debug)]
    struct UartRequest {
        data: u8,
        parity: ParityMode,
        inject_parity_error: bool,
        inject_stop_error: bool,
    }

    /// Requested parity encoding for a serial frame.
    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    enum ParityMode {
        Disabled,
        Even,
        Odd,
    }

    /// Requested or observed protocol corruption category.
    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    enum ErrorState {
        None,
        Parity,
        Stop,
        Both,
    }

    /// Data-value grouping used by protocol functional coverage.
    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    enum DataClass {
        Zero,
        Maximum,
        Alternating,
        Other,
    }

    /// Manual coverage collected from each independently transmitted frame.
    struct UartCoverage {
        instance: CoverageGroupInstance,
        parity_mode: Coverpoint<ParityMode>,
        error_injection: Coverpoint<ErrorState>,
        error_result: Coverpoint<ErrorState>,
        data_class: Coverpoint<DataClass>,
        parity_x_injection: Cross2,
    }

    impl UartCoverage {
        /// Builds the independent protocol coverpoints and their parity cross.
        fn new() -> Result<Self> {
            let parity_mode = Coverpoint::builder("parity_mode")
                .bin(Bin::value("disabled", ParityMode::Disabled))
                .bin(Bin::value("even", ParityMode::Even))
                .bin(Bin::value("odd", ParityMode::Odd))
                .build()?;
            let error_injection = error_coverpoint("error_injection")?;
            let error_result = error_coverpoint("error_result")?;
            let data_class = Coverpoint::builder("data_class")
                .bin(Bin::value("zero", DataClass::Zero))
                .bin(Bin::value("maximum", DataClass::Maximum))
                .bin(Bin::value("alternating", DataClass::Alternating))
                .bin(Bin::value("other", DataClass::Other))
                .build()?;
            let parity_x_injection =
                Cross2::builder("parity_x_injection", &parity_mode, &error_injection).build()?;

            Ok(Self {
                instance: CoverageGroupInstance::new("timed_uart", "dut.timed_uart")?,
                parity_mode,
                error_injection,
                error_result,
                data_class,
                parity_x_injection,
            })
        }

        /// Records one reconstructed frame in every protocol coverage dimension.
        fn sample(&mut self, request: UartRequest, frame: Frame) -> Result<()> {
            let parity_mode = self.parity_mode.sample(&request.parity)?;
            let error_injection = self.error_injection.sample(&injected_errors(request))?;
            self.error_result.sample(&observed_errors(request, frame))?;
            self.data_class.sample(&classify_data(request.data))?;

            self.parity_x_injection
                .sample(&parity_mode, &error_injection)?;

            Ok(())
        }
    }

    impl CoverageGroup for UartCoverage {
        /// Returns the stable hierarchical coverage identity.
        fn instance(&self) -> &CoverageGroupInstance {
            &self.instance
        }

        /// Visits items in deterministic report and artifact order.
        fn visit_items(&self, visitor: &mut dyn CoverageGroupVisitor) {
            visitor.visit(CoverageItemRef::coverpoint(&self.parity_mode));
            visitor.visit(CoverageItemRef::coverpoint(&self.error_injection));
            visitor.visit(CoverageItemRef::coverpoint(&self.error_result));
            visitor.visit(CoverageItemRef::coverpoint(&self.data_class));
            visitor.visit(CoverageItemRef::cross2(&self.parity_x_injection));
        }
    }

    /// Builds the four-state error-injection or decoded-error coverpoint.
    fn error_coverpoint(name: &'static str) -> Result<Coverpoint<ErrorState>> {
        Ok(Coverpoint::builder(name)
            .bin(Bin::value("none", ErrorState::None))
            .bin(Bin::value("parity", ErrorState::Parity))
            .bin(Bin::value("stop", ErrorState::Stop))
            .bin(Bin::value("both", ErrorState::Both))
            .build()?)
    }

    /// Converts requested corruption bits into a coverage error category.
    const fn injected_errors(request: UartRequest) -> ErrorState {
        match (request.inject_parity_error, request.inject_stop_error) {
            (false, false) => ErrorState::None,
            (true, false) => ErrorState::Parity,
            (false, true) => ErrorState::Stop,
            (true, true) => ErrorState::Both,
        }
    }

    /// Compares a decoded frame with its uncorrupted protocol expectation.
    fn observed_errors(request: UartRequest, frame: Frame) -> ErrorState {
        let uncorrupted = expected_frame(UartRequest {
            inject_parity_error: false,
            inject_stop_error: false,
            ..request
        });

        match (
            frame.parity != uncorrupted.parity,
            frame.stop != uncorrupted.stop,
        ) {
            (false, false) => ErrorState::None,
            (true, false) => ErrorState::Parity,
            (false, true) => ErrorState::Stop,
            (true, true) => ErrorState::Both,
        }
    }

    /// Groups values into directed protocol data classes.
    const fn classify_data(data: u8) -> DataClass {
        match data {
            0x00 => DataClass::Zero,
            u8::MAX => DataClass::Maximum,
            0x55 | 0xaa => DataClass::Alternating,
            _ => DataClass::Other,
        }
    }

    /// One serial level recorded at an internally scheduled time slot.
    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    struct Transition {
        time: SimulationTime,
        tx: bool,
    }

    /// A decoded UART frame, including corrupted protocol fields when injected.
    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    struct Frame {
        data: u8,
        parity: Option<bool>,
        stop: bool,
    }

    /// Drives inputs, runs delayed slots, and records the serial line at each slot.
    fn run(
        request: UartRequest,
        trace_path: Option<&Path>,
    ) -> Result<(Vec<Transition>, TimedUart)> {
        let mut dut = TimedUart::new()?;
        // The behavioral HDL samples these values during its initial process.
        dut.set_data(request.data)?;
        dut.set_parity_enable(request.parity != ParityMode::Disabled)?;
        dut.set_odd_parity(request.parity == ParityMode::Odd)?;
        dut.set_inject_parity_error(request.inject_parity_error)?;
        dut.set_inject_stop_error(request.inject_stop_error)?;

        if let Some(path) = trace_path {
            dut.open_trace(path)?;
        }

        let mut scheduler = TimingScheduler::new();
        // Initialization evaluates time zero; every later call advances to one
        // simulator-owned delayed slot.
        scheduler.initialize(&mut dut)?;
        let mut transitions = vec![Transition {
            time: SimulationTime::ZERO,
            tx: dut.tx()?,
        }];

        while let Some(event) = scheduler.advance_next(&mut dut)? {
            transitions.push(Transition {
                time: event.time(),
                tx: dut.tx()?,
            });
        }

        Ok((transitions, dut))
    }

    /// Reconstructs start, data, optional parity, and stop fields from slots.
    fn decode(request: UartRequest, transitions: &[Transition]) -> Frame {
        // A transition entry exists for each bit boundary, so reconstruct the
        // frame from levels instead of mirroring the HDL delay statements.
        let levels = transitions
            .iter()
            .map(|transition| transition.tx)
            .collect::<Vec<_>>();
        assert!(levels.first().copied().unwrap_or(false));
        assert!(!levels.get(1).copied().unwrap_or(true));

        let data = levels
            .get(2..10)
            .unwrap_or_default()
            .iter()
            .enumerate()
            .fold(0_u8, |value, (bit, level)| {
                value | (u8::from(*level) << bit)
            });
        let parity_index = 10_usize;
        let parity_enabled = request.parity != ParityMode::Disabled;
        let parity = parity_enabled.then(|| levels.get(parity_index).copied().unwrap_or_default());
        let stop_index = parity_index
            .checked_add(usize::from(parity_enabled))
            .unwrap_or_default();

        Frame {
            data,
            parity,
            stop: levels.get(stop_index).copied().unwrap_or_default(),
        }
    }

    /// Calculates the protocol frame expected before any simulated corruption.
    fn expected_frame(request: UartRequest) -> Frame {
        let parity = (request.parity != ParityMode::Disabled).then(|| {
            (!request.data.count_ones().is_multiple_of(2))
                ^ (request.parity == ParityMode::Odd)
                ^ request.inject_parity_error
        });
        Frame {
            data: request.data,
            parity,
            stop: !request.inject_stop_error,
        }
    }

    /// Runs one frame, validates its protocol fields, and explicitly finalizes it.
    fn verify_frame(request: UartRequest) -> Result<(Frame, SimulationTime)> {
        let (transitions, mut dut) = run(request, None)?;
        let frame = decode(request, &transitions);

        // Compare a protocol model to the reconstructed serial frame.
        assert_eq!(frame, expected_frame(request));
        assert!(dut.done()?);
        assert!(!dut.busy()?);
        assert!(dut.tx()?);
        assert!(
            transitions
                .windows(2)
                .all(|window| matches!(window, [first, second] if first.time < second.time))
        );

        let final_time = dut.simulation_time();
        dut.finish()?;

        Ok((frame, final_time))
    }

    /// Runs one frame when the caller only needs pass/fail verification.
    fn verify(request: UartRequest) -> Result<()> {
        let _ = verify_frame(request)?;

        Ok(())
    }

    /// Transmits zero and records the VCD-capable timed event sequence.
    #[test]
    fn uart_transmits_known_byte() -> Result<()> {
        verify(UartRequest {
            data: 0x00,
            parity: ParityMode::Even,
            inject_parity_error: false,
            inject_stop_error: false,
        })
    }

    /// Omits parity while preserving start, data, stop, and final-idle events.
    #[test]
    fn uart_transmits_without_parity() -> Result<()> {
        verify(UartRequest {
            data: 0xaa,
            parity: ParityMode::Disabled,
            inject_parity_error: false,
            inject_stop_error: false,
        })
    }

    /// Uses even parity for a maximum byte value.
    #[test]
    fn uart_transmits_even_parity() -> Result<()> {
        verify(UartRequest {
            data: 0xff,
            parity: ParityMode::Even,
            inject_parity_error: false,
            inject_stop_error: false,
        })
    }

    /// Uses odd parity for an alternating byte pattern.
    #[test]
    fn uart_transmits_odd_parity() -> Result<()> {
        verify(UartRequest {
            data: 0x55,
            parity: ParityMode::Odd,
            inject_parity_error: false,
            inject_stop_error: false,
        })
    }

    /// Reconstructs and identifies an intentionally corrupted parity field.
    #[test]
    fn uart_detects_injected_parity_error() -> Result<()> {
        let request = UartRequest {
            data: 0x3c,
            parity: ParityMode::Even,
            inject_parity_error: true,
            inject_stop_error: false,
        };
        let (transitions, mut dut) = run(request, None)?;
        assert_ne!(
            decode(request, &transitions).parity,
            expected_frame(UartRequest {
                inject_parity_error: false,
                ..request
            })
            .parity
        );
        dut.finish()?;
        Ok(())
    }

    /// Reconstructs and identifies an intentionally low stop bit.
    #[test]
    fn uart_detects_injected_stop_error() -> Result<()> {
        verify(UartRequest {
            data: 0xc3,
            parity: ParityMode::Odd,
            inject_parity_error: false,
            inject_stop_error: true,
        })
    }

    /// Runs replayable random frames and captures protocol-level functional coverage.
    #[vvm::test(replay(default = UART_RANDOM_REPLAY), coverage)]
    fn uart_random_frames(context: &mut TestContext) -> Result<TestResult<(), String, Error>> {
        let replay = context.config().replay_token_or(UART_RANDOM_REPLAY);
        let mut random = RandomContext::from_replay(replay);
        let mut coverage = UartCoverage::new()?;
        let mut final_time = SimulationTime::ZERO;

        for index in 0..24_u8 {
            // Directed prefix covers every bin; the remaining frames exercise
            // the same decoder with replayable randomized values.
            let request = random_request(index, &mut random);
            let (frame, time) = verify_frame(request)?;

            coverage.sample(request, frame)?;
            final_time = time;
        }

        context.capture_coverage(&coverage)?;

        Ok(TestResult::completed(
            SimulationTime::ZERO,
            final_time,
            Some(replay),
        ))
    }

    /// Stable replay stream for the frame-coverage regression.
    const UART_RANDOM_REPLAY: ReplayToken = ReplayToken::new(Seed::new(0x75_a4_21_9c));

    /// Combines directed frame classes with replayable random frame generation.
    fn random_request(index: u8, random: &mut RandomContext) -> UartRequest {
        let data = match index {
            0 => 0x00,
            1 => u8::MAX,
            2 => 0x55,
            3 => 0xaa,
            _ => u8::try_from(random.next_u32() & 0xff).unwrap_or_default(),
        };
        let parity = match if index < 12 {
            u32::from(index % 3)
        } else {
            random.next_u32() % 3
        } {
            0 => ParityMode::Disabled,
            1 => ParityMode::Even,
            _ => ParityMode::Odd,
        };
        let error_bits = if index < 12 {
            /// Directed corruption combinations cover every error-state bin.
            const DIRECTED_ERROR_BITS: [u8; 12] = [0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3];

            DIRECTED_ERROR_BITS
                .get(usize::from(index))
                .copied()
                .unwrap_or_default()
        } else {
            u8::try_from(random.next_u32() & 0b11).unwrap_or_default()
        };

        UartRequest {
            data,
            parity,
            inject_parity_error: error_bits & 1 != 0,
            inject_stop_error: error_bits & 2 != 0,
        }
    }

    /// Writes a VCD containing the complete timed transmission and finalization.
    #[test]
    fn uart_generates_trace() -> Result<()> {
        let directory = tempfile::tempdir()?;
        let trace_path = directory.path().join("timed-uart.vcd");
        let request = UartRequest {
            data: 0xa5,
            parity: ParityMode::Even,
            inject_parity_error: false,
            inject_stop_error: false,
        };
        let (_, mut dut) = run(request, Some(&trace_path))?;

        dut.finish()?;
        let contents = std::fs::read_to_string(trace_path)?;
        assert!(contents.contains("$enddefinitions"));
        assert!(contents.contains("tx"));
        assert!(contents.contains("#10"));

        Ok(())
    }
}
