[package]
name = "vvm-core"
version.workspace       = true
authors.workspace       = true
edition.workspace       = true
rust-version.workspace  = true
homepage.workspace      = true
repository.workspace    = true
license.workspace       = true
keywords.workspace      = true
categories.workspace    = true
description             = "VVM core verification APIs"
readme                  = "README.md"
documentation           = "https://byacrates.gitlab.io/vvm-rs/api/vvm_core/"

[lib]
bench = false

[lints]
workspace = true

[dependencies]
rand_chacha.workspace = true
rand_core.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true

[dev-dependencies]
criterion.workspace = true
proptest.workspace = true

[[bench]]
name = "packed"
harness = false

[[bench]]
name = "random"
harness = false

[[bench]]
name = "scoreboard"
harness = false

[[bench]]
name = "schedulers"
harness = false

[[bench]]
name = "coverage"
harness = false

[package.metadata.cargo-udeps.ignore]
normal = [
    "vvm",
    "vvm-build",
    "vvm-core",
    "vvm-macros",
]
development = ["criterion"]
