[package]
name = "cargo-vvm"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
description = "Cargo subcommand for VVM functional coverage orchestration"
readme = "README.md"
documentation = "https://byacrates.gitlab.io/vvm-rs/cargo-vvm.html"
publish = false

[[bin]]
name = "cargo-vvm"
path = "src/main.rs"
bench = false

[lints]
workspace = true

[dependencies]
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
vvm-core.workspace = true

[dev-dependencies]
criterion.workspace = true
assert_cmd.workspace = true
predicates.workspace = true
tempfile.workspace = true

[[bench]]
name = "orchestration"
harness = false

[package.metadata.cargo-udeps.ignore]
development = ["assert_cmd", "predicates"]
