[package]
name = "vvm-rs"
version.workspace       = true
authors.workspace       = true
edition.workspace       = true
rust-version.workspace  = true
homepage.workspace      = true
repository.workspace    = true
license.workspace       = true
keywords.workspace      = true
categories.workspace    = true
description             = "VVM public facade"

[lib]
name = "vvm"
bench = false

[lints]
workspace = true

[features]
default = []
full = []

[package.metadata.cargo-udeps.ignore]
normal = [
    "vvm-build",
    "vvm-core",
    "vvm-macros",
]
