[package]
name = "vvm-rs"
version.workspace       = true
authors.workspace       = true
edition.workspace       = true
rust-version.workspace  = true
homepage.workspace      = true
repository.workspace    = true
license.workspace       = true
keywords.workspace      = true
categories.workspace    = true
description             = "Verilator Verification Methodology for Rust"

[lib]
name = "vvm"
bench = false

[lints]
workspace = true

[dependencies]
vvm-core.workspace = true
vvm-macros.workspace = true
cxx.workspace = true
