/// C++ adapter source generation.
pub mod cpp_adapter;
/// Raw CXX bridge source generation.
pub mod cxx_bridge;
/// Deterministic generated C++ naming.
pub mod names;
/// Safe Rust DUT wrapper generation.
pub mod rust_wrapper;
/// Generated signal type selection.
pub mod types;
/// Deterministic generated-file writing.
pub mod writer;

use std::fs;
use std::path::{Path, PathBuf};

use crate::metadata::DutMetadata;
use crate::{BuildError, BuildResult, TraceOptions};

/// Deterministic notice placed at the beginning of generated source files.
const GENERATED_NOTICE: &str = "// @generated by vvm-build. Do not edit.";

/// Generated DUT integration artifacts
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedArtifacts {
    /// Directory containing the generated public header.
    pub(crate) include_dir: PathBuf,

    /// Generated C++ adapter header.
    pub(crate) cpp_header: PathBuf,

    /// Generated C++ adapter source.
    pub(crate) cpp_source: PathBuf,

    /// Generated raw CXX bridge.
    pub(crate) cxx_bridge: PathBuf,

    /// Generated safe Rust DUT wrapper.
    pub(crate) rust_wrapper: PathBuf,
}

/// Generates the C++ adapter for one normalized DUT.
///
/// # Errors
///
/// Returns an error when generated names are invalid or output files cannot
/// be created.
pub fn generate(
    metadata: &DutMetadata,
    model_prefix: &str,
    output_dir: &Path,
    trace: Option<TraceOptions>,
    timing: bool,
) -> BuildResult<GeneratedArtifacts> {
    let names = names::resolve(metadata, model_prefix)?;
    let adapter = cpp_adapter::render(metadata, &names, trace, timing);
    let bridge = cxx_bridge::render(metadata, &names, trace, timing);
    let wrapper = rust_wrapper::render(metadata, &names, trace, timing);

    fs::create_dir_all(output_dir).map_err(|source| BuildError::Io {
        operation: "create generated source directory",
        path: output_dir.to_path_buf(),
        source,
    })?;

    let cpp_header = output_dir.join(format!("{}.hpp", names.file_stem));
    let cpp_source = output_dir.join(format!("{}.cpp", names.file_stem));
    let cxx_bridge = output_dir.join("bridge.rs");
    let rust_wrapper = output_dir.join("dut.rs");

    writer::write_if_changed(&cpp_header, &adapter.header)?;
    writer::write_if_changed(&cpp_source, &adapter.source)?;
    writer::write_if_changed(&cxx_bridge, &bridge)?;
    writer::write_if_changed(&rust_wrapper, &wrapper)?;

    Ok(GeneratedArtifacts {
        include_dir: output_dir.to_path_buf(),
        cpp_header,
        cpp_source,
        cxx_bridge,
        rust_wrapper,
    })
}

#[cfg(test)]
mod tests {
    use std::num::NonZeroU32;
    use std::path::{Path, PathBuf};

    use tempfile::tempdir;

    use super::generate;
    use crate::TraceOptions;
    use crate::metadata::{
        BitWidth, DutMetadata, PackedScalarShape, Port, PortDirection, PortShape, RawMetadata,
        normalize,
    };
    use crate::verilator::VerilatorVersion;

    fn wide_ports_metadata() -> Result<DutMetadata, Box<dyn std::error::Error>> {
        let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));

        let metadata_fixture = manifest
            .join("tests")
            .join("fixtures")
            .join("verilator")
            .join("5.048")
            .join("wide_ports");

        let raw = RawMetadata::from_paths(
            VerilatorVersion::new(5, 48),
            &metadata_fixture.join("wide_ports.tree.json"),
            &metadata_fixture.join("wide_ports.tree.meta.json"),
        )?;

        Ok(normalize("wide_ports", "wide_ports", &raw)?)
    }

    fn counter_metadata() -> Result<crate::metadata::DutMetadata, Box<dyn std::error::Error>> {
        let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));

        let metadata_fixture = manifest
            .join("tests")
            .join("fixtures")
            .join("verilator")
            .join("5.048")
            .join("counter");

        let raw = RawMetadata::from_paths(
            VerilatorVersion::new(5, 48),
            &metadata_fixture.join("counter.tree.json"),
            &metadata_fixture.join("counter.tree.meta.json"),
        )?;

        Ok(normalize("counter", "counter", &raw)?)
    }

    fn signed_ports_metadata() -> Result<crate::metadata::DutMetadata, Box<dyn std::error::Error>> {
        let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));

        let metadata_fixture = manifest
            .join("tests")
            .join("fixtures")
            .join("verilator")
            .join("5.048")
            .join("signed_ports");

        let raw = RawMetadata::from_paths(
            VerilatorVersion::new(5, 48),
            &metadata_fixture.join("signed_ports.tree.json"),
            &metadata_fixture.join("signed_ports.tree.meta.json"),
        )?;

        Ok(normalize("signed_ports", "signed_ports", &raw)?)
    }

    fn packed_array_ports_metadata()
    -> Result<crate::metadata::DutMetadata, Box<dyn std::error::Error>> {
        let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));

        let metadata_fixture = manifest
            .join("tests")
            .join("fixtures")
            .join("verilator")
            .join("5.048")
            .join("packed_array_ports");

        let raw = RawMetadata::from_paths(
            VerilatorVersion::new(5, 48),
            &metadata_fixture.join("packed_array_ports.tree.json"),
            &metadata_fixture.join("packed_array_ports.tree.meta.json"),
        )?;

        Ok(normalize("packed_array_ports", "packed_array_ports", &raw)?)
    }

    fn unpacked_array_ports_metadata() -> Result<DutMetadata, Box<dyn std::error::Error>> {
        let fixture = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("tests/fixtures/verilator/5.048/unpacked_array_ports");
        let raw = RawMetadata::from_paths(
            VerilatorVersion::new(5, 48),
            &fixture.join("unpacked_array_ports.tree.json"),
            &fixture.join("unpacked_array_ports.tree.meta.json"),
        )?;
        Ok(normalize(
            "unpacked_array_ports",
            "unpacked_array_ports",
            &raw,
        )?)
    }

    fn packed_struct_ports_metadata()
    -> Result<crate::metadata::DutMetadata, Box<dyn std::error::Error>> {
        let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));

        let metadata_fixture = manifest
            .join("tests")
            .join("fixtures")
            .join("verilator")
            .join("5.048")
            .join("packed_struct_ports");

        let raw = RawMetadata::from_paths(
            VerilatorVersion::new(5, 48),
            &metadata_fixture.join("packed_struct_ports.tree.json"),
            &metadata_fixture.join("packed_struct_ports.tree.meta.json"),
        )?;

        Ok(normalize(
            "packed_struct_ports",
            "packed_struct_ports",
            &raw,
        )?)
    }

    fn packed_enum_ports_metadata()
    -> Result<crate::metadata::DutMetadata, Box<dyn std::error::Error>> {
        let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));

        let metadata_fixture = manifest
            .join("tests")
            .join("fixtures")
            .join("verilator")
            .join("5.048")
            .join("packed_enum_ports");

        let raw = RawMetadata::from_paths(
            VerilatorVersion::new(5, 48),
            &metadata_fixture.join("packed_enum_ports.tree.json"),
            &metadata_fixture.join("packed_enum_ports.tree.meta.json"),
        )?;

        Ok(normalize("packed_enum_ports", "packed_enum_ports", &raw)?)
    }

    fn expected_codegen_directory(name: &str) -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("tests")
            .join("fixtures")
            .join("codegen")
            .join(name)
    }

    fn expected_codegen_contract_path(name: &str) -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("tests")
            .join("fixtures")
            .join("codegen-contracts")
            .join(name)
    }

    fn assert_generated_artifacts_match(
        generated: &super::GeneratedArtifacts,
        expected_directory: &Path,
        file_stem: &str,
    ) -> Result<(), Box<dyn std::error::Error>> {
        assert_generated_snapshot(
            &generated.cpp_header,
            &expected_directory.join(format!("{file_stem}.hpp")),
        )?;
        assert_generated_snapshot(
            &generated.cpp_source,
            &expected_directory.join(format!("{file_stem}.cpp")),
        )?;
        assert_generated_snapshot(&generated.cxx_bridge, &expected_directory.join("bridge.rs"))?;
        assert_generated_snapshot(&generated.rust_wrapper, &expected_directory.join("dut.rs"))?;

        Ok(())
    }

    fn assert_same_generated_contents(
        first: &super::GeneratedArtifacts,
        second: &super::GeneratedArtifacts,
    ) -> Result<(), Box<dyn std::error::Error>> {
        assert_eq!(
            std::fs::read_to_string(&first.cpp_header)?,
            std::fs::read_to_string(&second.cpp_header)?
        );
        assert_eq!(
            std::fs::read_to_string(&first.cpp_source)?,
            std::fs::read_to_string(&second.cpp_source)?
        );
        assert_eq!(
            std::fs::read_to_string(&first.cxx_bridge)?,
            std::fs::read_to_string(&second.cxx_bridge)?
        );
        assert_eq!(
            std::fs::read_to_string(&first.rust_wrapper)?,
            std::fs::read_to_string(&second.rust_wrapper)?
        );

        Ok(())
    }

    fn assert_generated_snapshot(
        actual_path: &Path,
        expected_path: &Path,
    ) -> Result<(), Box<dyn std::error::Error>> {
        let actual = std::fs::read_to_string(actual_path)?;
        let expected = std::fs::read_to_string(expected_path)?;

        assert_eq!(
            actual,
            expected,
            "generated artifact `{}` differs from its snapshot",
            actual_path.display()
        );

        assert!(
            actual.ends_with('\n'),
            "generated artifact must end with a newline: {}",
            actual_path.display()
        );

        assert!(
            !actual.contains('\r'),
            "generated artifact must use Unix newlines: {}",
            actual_path.display()
        );

        assert!(
            !actual.contains(env!("CARGO_MANIFEST_DIR")),
            "generated artifact contains a host checkout path: {}",
            actual_path.display()
        );

        Ok(())
    }

    fn assert_contract_fixture(
        fixture_name: &str,
        header: &str,
        source: &str,
        bridge: &str,
        wrapper: &str,
    ) -> Result<(), Box<dyn std::error::Error>> {
        let fixture = std::fs::read_to_string(expected_codegen_contract_path(fixture_name))?;

        for line in fixture.lines().filter(|line| !line.is_empty()) {
            let (target, expected) = line.split_once(':').ok_or_else(|| {
                std::io::Error::new(
                    std::io::ErrorKind::InvalidData,
                    format!("invalid contract fixture line `{line}`"),
                )
            })?;

            let actual = match target {
                "header" => header,
                "source" => source,
                "bridge" => bridge,
                "wrapper" => wrapper,
                _ => {
                    return Err(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        format!("unknown contract fixture target `{target}`"),
                    )
                    .into());
                }
            };

            assert!(
                actual.contains(expected),
                "generated {target} artifact does not contain expected contract fragment \
                 `{expected}`"
            );
        }

        Ok(())
    }

    fn scalar_port(name: &str, direction: PortDirection, width: BitWidth, signed: bool) -> Port {
        Port {
            name: name.to_owned(),
            direction,
            width,
            signed,
            shape: PortShape::PackedScalar(PackedScalarShape { width, signed }),
        }
    }

    #[test]
    fn generated_artifacts_include_inout_access() -> Result<(), Box<dyn std::error::Error>> {
        let width = BitWidth::new(NonZeroU32::MIN);
        let metadata = DutMetadata {
            name: String::from("inout_ports"),
            top_module: String::from("inout_ports"),
            ports: vec![scalar_port("bus", PortDirection::Inout, width, false)],
        };
        let output = tempdir()?;
        let generated = generate(&metadata, "Vinout_ports", output.path(), None, false)?;

        let header = std::fs::read_to_string(&generated.cpp_header)?;
        let source = std::fs::read_to_string(&generated.cpp_source)?;
        let bridge = std::fs::read_to_string(&generated.cxx_bridge)?;
        let wrapper = std::fs::read_to_string(&generated.rust_wrapper)?;

        assert!(header.contains("set_bus_input"));
        assert!(header.contains("bus_input"));
        assert!(header.contains("bus_output_enable"));
        assert!(header.contains("bus_output_value"));
        assert!(source.contains("model->bus = raw_value"));
        assert!(source.contains("model->bus__en"));
        assert!(source.contains("model->bus__out"));
        assert!(bridge.contains("fn set_bus_input"));
        assert!(bridge.contains("fn bus_input"));
        assert!(bridge.contains("fn bus_output_enable"));
        assert!(bridge.contains("fn bus_output_value"));
        assert!(wrapper.contains("pub fn set_bus_input"));
        assert!(wrapper.contains("pub fn set_bus(&mut self"));
        assert!(
            wrapper
                .contains("pub fn bus(&self) -> Result<::vvm::__private::InoutState<bool, bool>>")
        );
        assert!(!wrapper.contains("pub fn drive_bus"));
        assert!(!wrapper.contains("pub fn release_bus"));

        assert_contract_fixture("inout_ports.txt", &header, &source, &bridge, &wrapper)?;

        Ok(())
    }

    fn assert_wide_header_artifacts(header: &str) {
        assert!(header.contains("#include \"rust/cxx.h\""));
        for width in [65, 96, 129, 256] {
            assert!(header.contains(&format!(
                "bool set_input_u{width}(rust::Slice<const std::uint32_t> words) noexcept;"
            )));
            assert!(header.contains(&format!(
                "bool output_u{width}(rust::Slice<std::uint32_t> words) const noexcept;"
            )));
        }
        for width in [65, 129] {
            assert!(header.contains(&format!(
                "bool set_input_i{width}(rust::Slice<const std::uint32_t> words) noexcept;"
            )));
            assert!(header.contains(&format!(
                "bool output_i{width}(rust::Slice<std::uint32_t> words) const noexcept;"
            )));
        }
        assert!(!header.contains("set_input_u65(std::uint64_t value) noexcept"));
        assert!(!header.contains("set_input_u96(std::uint64_t value) noexcept"));
        assert!(!header.contains("output_u96() const noexcept"));
        assert!(!header.contains("output_u256() const noexcept"));
    }

    fn assert_wide_source_artifacts(source: &str) {
        for word_count in [3, 5, 8] {
            assert!(source.contains(&format!(
                "constexpr std::size_t expected_words{{{word_count}}};"
            )));
        }
        assert!(source.contains("static_assert(RawType::Words == expected_words);"));
        assert!(source.contains("if (words.size() != expected_words) {"));
        assert!(source.contains("return false;"));
        assert!(source.contains("raw_value[index] = words[index];"));
        assert!(source.contains("words[index] = raw_value[index];"));
        for index in [2, 4] {
            assert!(source.contains(&format!("raw_value[{index}] &= 0x1U;")));
            assert!(source.contains(&format!("words[{index}] &= 0x1U;")));
        }
        for index in [2, 7] {
            assert!(!source.contains(&format!("raw_value[{index}] &= 0xFFFFFFFFU;")));
            assert!(!source.contains(&format!("words[{index}] &= 0xFFFFFFFFU;")));
        }
    }

    fn assert_wide_bridge_artifacts(bridge: &str) {
        for width in [65, 96, 129, 256] {
            assert!(bridge.contains(&format!(
                "fn set_input_u{width}(self: Pin<&mut WidePorts>, words: &[u32]) -> bool;"
            )));
            assert!(bridge.contains(&format!(
                "fn output_u{width}(self: &WidePorts, words: &mut [u32]) -> bool;"
            )));
        }
        for width in [65, 129] {
            assert!(bridge.contains(&format!(
                "fn set_input_i{width}(self: Pin<&mut WidePorts>, words: &[u32]) -> bool;"
            )));
            assert!(bridge.contains(&format!(
                "fn output_i{width}(self: &WidePorts, words: &mut [u32]) -> bool;"
            )));
        }
    }

    fn assert_wide_wrapper_artifacts(wrapper: &str) {
        for width in [65, 96, 129, 256] {
            assert!(wrapper.contains(&format!(
                "value: impl ::core::borrow::Borrow<::vvm::__private::Bits<{width}>>"
            )));
            assert!(wrapper.contains(&format!(
                "pub fn output_u{width}(&self) -> Result<::vvm::__private::Bits<{width}>> {{"
            )));
            assert!(wrapper.contains(&format!(
                "vec![0_u32; ::vvm::__private::Bits::<{width}>::WORDS];"
            )));
        }
        for width in [65, 129] {
            assert!(wrapper.contains(&format!(
                "value: impl ::core::borrow::Borrow<::vvm::__private::SignedBits<{width}>>"
            )));
            assert!(wrapper.contains(&format!(
                "pub fn output_i{width}(&self) -> Result<::vvm::__private::SignedBits<{width}>> {{"
            )));
            assert!(wrapper.contains(&format!(
                "vec![0_u32; ::vvm::__private::SignedBits::<{width}>::WORDS];"
            )));
        }
        assert!(wrapper.contains("WidePortTransferFailed"));
        assert!(wrapper.contains(".map_err(|_error| {"));
    }

    #[test]
    fn generates_expected_counter_artifacts() -> Result<(), Box<dyn std::error::Error>> {
        let metadata = counter_metadata()?;
        let output = tempdir()?;
        let generated = generate(&metadata, "Vcounter", output.path(), None, false)?;
        let expected_directory = expected_codegen_directory("counter");

        assert_generated_artifacts_match(&generated, &expected_directory, "counter")?;

        let header = std::fs::read_to_string(&generated.cpp_header)?;
        let source = std::fs::read_to_string(&generated.cpp_source)?;
        let bridge = std::fs::read_to_string(&generated.cxx_bridge)?;
        let wrapper = std::fs::read_to_string(&generated.rust_wrapper)?;

        assert!(!header.contains("rust/cxx.h"));
        assert!(!header.contains("open_trace"));
        assert!(!source.contains("VerilatedVcdC"));
        assert!(!source.contains("traceEverOn"));
        assert!(!bridge.contains("open_trace"));
        assert!(!wrapper.contains("TraceAfterEvaluation"));
        assert!(!wrapper.contains("TraceableDut"));
        assert!(!wrapper.contains(".pin_mut()"));
        assert!(!wrapper.contains("unsafe"));
        assert!(!wrapper.contains("Vcounter"));
        assert!(wrapper.contains("pub enum CounterError"));
        assert!(wrapper.contains("impl ::vvm::__private::Dut for Counter"));
        assert!(wrapper.contains("impl Drop for Counter"));
        assert!(wrapper.contains("impl std::fmt::Debug for Counter"));

        Ok(())
    }

    #[test]
    fn timing_codegen_emits_queries_and_keeps_ordinary_output_unchanged()
    -> Result<(), Box<dyn std::error::Error>> {
        let metadata = counter_metadata()?;
        let ordinary_output = tempdir()?;
        let timing_output = tempdir()?;
        let ordinary = generate(&metadata, "Vcounter", ordinary_output.path(), None, false)?;
        let timed = generate(&metadata, "Vcounter", timing_output.path(), None, true)?;
        let ordinary_header = std::fs::read_to_string(ordinary.cpp_header)?;
        let timed_header = std::fs::read_to_string(timed.cpp_header)?;
        let timed_source = std::fs::read_to_string(timed.cpp_source)?;
        let timed_bridge = std::fs::read_to_string(timed.cxx_bridge)?;
        let timed_wrapper = std::fs::read_to_string(timed.rust_wrapper)?;

        assert!(!ordinary_header.contains("events_pending"));
        assert!(timed_header.contains("events_pending"));
        assert!(timed_header.contains("std::uint64_t& time"));
        let guard = timed_source
            .find("eventsPending()")
            .ok_or("missing pending guard")?;
        let slot = timed_source
            .find("nextTimeSlot()")
            .ok_or("missing slot query")?;
        assert!(guard < slot);
        assert!(timed_bridge.contains("fn events_pending"));
        assert!(timed_bridge.contains("time: &mut u64"));
        assert!(timed_wrapper.contains("pub fn next_time_slot"));
        assert!(timed_wrapper.contains("impl ::vvm::__private::TimedDut"));
        assert_contract_fixture(
            "counter_timing.txt",
            &timed_header,
            &timed_source,
            &timed_bridge,
            &timed_wrapper,
        )?;
        Ok(())
    }

    #[test]
    fn generates_signed_port_artifacts_from_fixture() -> Result<(), Box<dyn std::error::Error>> {
        let metadata = signed_ports_metadata()?;
        let output = tempdir()?;
        let generated = generate(&metadata, "Vsigned_ports", output.path(), None, false)?;

        let header = std::fs::read_to_string(&generated.cpp_header)?;
        let source = std::fs::read_to_string(&generated.cpp_source)?;
        let bridge = std::fs::read_to_string(&generated.cxx_bridge)?;
        let wrapper = std::fs::read_to_string(&generated.rust_wrapper)?;

        assert!(header.contains("void set_input_i1(std::int8_t value) noexcept;"));
        assert!(header.contains("void set_input_i5(std::int8_t value) noexcept;"));
        assert!(header.contains("void set_input_i9(std::int16_t value) noexcept;"));
        assert!(header.contains("void set_input_i17(std::int32_t value) noexcept;"));
        assert!(header.contains("void set_input_i33(std::int64_t value) noexcept;"));
        assert!(header.contains("void set_input_i64(std::int64_t value) noexcept;"));
        assert!(header.contains("std::int8_t output_i1() const noexcept;"));
        assert!(header.contains("std::int64_t output_i64() const noexcept;"));

        assert!(source.contains("    }\n\n    template <typename Signed,"));
        assert!(source.contains("using UnsignedType = std::uint8_t;"));
        assert!(source.contains("using UnsignedType = std::uint16_t;"));
        assert!(source.contains("using UnsignedType = std::uint32_t;"));
        assert!(source.contains("using UnsignedType = std::uint64_t;"));
        assert!(source.contains("static_cast<std::uint8_t>(0x1FULL)"));
        assert!(source.contains("Impl::sign_extend<std::int8_t, 1>("));
        assert!(source.contains("Impl::sign_extend<std::int8_t, 5>("));
        assert!(source.contains("Impl::sign_extend<std::int16_t, 9>("));
        assert!(source.contains("Impl::sign_extend<std::int32_t, 17>("));
        assert!(source.contains("Impl::sign_extend<std::int64_t, 33>("));
        assert!(source.contains("Impl::sign_extend<std::int64_t, 64>("));

        assert!(bridge.contains("fn set_input_i1(self: Pin<&mut SignedPorts>, value: i8);"));
        assert!(bridge.contains("fn set_input_i9(self: Pin<&mut SignedPorts>, value: i16);"));
        assert!(bridge.contains("fn set_input_i17(self: Pin<&mut SignedPorts>, value: i32);"));
        assert!(bridge.contains("fn set_input_i33(self: Pin<&mut SignedPorts>, value: i64);"));
        assert!(bridge.contains("fn output_i1(self: &SignedPorts) -> i8;"));
        assert!(bridge.contains("fn output_i64(self: &SignedPorts) -> i64;"));

        assert!(wrapper.contains("value: impl ::core::borrow::Borrow<i8>"));
        assert!(wrapper.contains("value: impl ::core::borrow::Borrow<i16>"));
        assert!(wrapper.contains("value: impl ::core::borrow::Borrow<i32>"));
        assert!(wrapper.contains("value: impl ::core::borrow::Borrow<i64>"));
        assert!(wrapper.contains("*::core::borrow::Borrow::borrow(&value)"));
        assert!(wrapper.contains("pub fn output_i1(&self) -> Result<i8> {"));
        assert!(wrapper.contains("pub fn output_i64(&self) -> Result<i64> {"));

        Ok(())
    }

    #[test]
    fn generates_expected_traced_counter_artifacts() -> Result<(), Box<dyn std::error::Error>> {
        let metadata = counter_metadata()?;
        let output = tempdir()?;
        let generated = generate(
            &metadata,
            "Vcounter",
            output.path(),
            Some(TraceOptions::vcd()),
            false,
        )?;
        let expected_directory = expected_codegen_directory("counter-vcd");

        assert_generated_artifacts_match(&generated, &expected_directory, "counter")?;

        let header = std::fs::read_to_string(&generated.cpp_header)?;
        let source = std::fs::read_to_string(&generated.cpp_source)?;
        let bridge = std::fs::read_to_string(&generated.cxx_bridge)?;
        let wrapper = std::fs::read_to_string(&generated.rust_wrapper)?;

        assert!(header.contains("rust/cxx.h"));
        assert!(header.contains("open_trace"));
        assert!(header.contains("close_trace"));
        assert!(header.contains("trace_is_open"));
        assert!(!header.contains("VerilatedVcdC"));
        assert!(source.contains("context->traceEverOn(true)"));
        assert!(source.contains("std::unique_ptr<VerilatedVcdC>"));
        assert!(source.contains("impl_->model->trace(impl_->trace.get(), 99);"));
        assert!(source.contains("trace->dump"));
        assert!(source.contains("trace->flush"));
        assert!(source.contains("trace->close"));
        assert!(source.contains("last_trace_time"));
        assert!(source.contains("has_trace_dump"));
        assert!(bridge.contains("fn open_trace"));
        assert!(bridge.contains("fn close_trace"));
        assert!(bridge.contains("fn trace_is_open"));
        assert!(bridge.contains("path: &str"));
        assert!(wrapper.contains("TraceAfterEvaluation"));
        assert!(wrapper.contains("TraceAlreadyConfigured"));
        assert!(wrapper.contains("TracePathNotUtf8"));
        assert!(wrapper.contains("TraceOpenFailed"));
        assert!(wrapper.contains("evaluated"));
        assert!(wrapper.contains("trace_configured"));
        assert!(wrapper.contains("trace_open"));
        assert!(wrapper.contains("impl ::vvm::__private::TraceableDut"));
        assert!(wrapper.contains("impl ::vvm::__private::Dut"));
        assert!(wrapper.contains("SimulationTime"));
        assert!(wrapper.contains("advance_time"));
        assert!(wrapper.contains("Drop"));

        let trace_ever_on = source.find("context->traceEverOn(true)").ok_or_else(|| {
            std::io::Error::new(std::io::ErrorKind::InvalidData, "missing traceEverOn")
        })?;
        let model_construction = source
            .find("model = std::make_unique<Vcounter>(context.get());")
            .ok_or_else(|| {
                std::io::Error::new(
                    std::io::ErrorKind::InvalidData,
                    "missing traced model construction",
                )
            })?;

        assert!(trace_ever_on < model_construction);

        Ok(())
    }

    #[test]
    fn generates_deterministic_output() -> Result<(), Box<dyn std::error::Error>> {
        let metadata = counter_metadata()?;

        let first_output = tempdir()?;
        let second_output = tempdir()?;
        let traced_first_output = tempdir()?;
        let traced_second_output = tempdir()?;

        let first = generate(&metadata, "Vcounter", first_output.path(), None, false)?;
        let second = generate(&metadata, "Vcounter", second_output.path(), None, false)?;
        let traced_first = generate(
            &metadata,
            "Vcounter",
            traced_first_output.path(),
            Some(TraceOptions::vcd()),
            false,
        )?;
        let traced_second = generate(
            &metadata,
            "Vcounter",
            traced_second_output.path(),
            Some(TraceOptions::vcd()),
            false,
        )?;

        assert_same_generated_contents(&first, &second)?;
        assert_same_generated_contents(&traced_first, &traced_second)?;

        Ok(())
    }

    #[test]
    fn traced_wrapper_generation_encodes_trace_lifecycle_rules()
    -> Result<(), Box<dyn std::error::Error>> {
        let metadata = counter_metadata()?;
        let output = tempdir()?;
        let generated = generate(
            &metadata,
            "Vcounter",
            output.path(),
            Some(TraceOptions::vcd()),
            false,
        )?;

        let bridge = std::fs::read_to_string(&generated.cxx_bridge)?;
        let wrapper = std::fs::read_to_string(&generated.rust_wrapper)?;

        assert!(wrapper.contains("if self.evaluated.is_set() {"));
        assert!(wrapper.contains("TraceAfterEvaluation"));
        assert!(wrapper.contains("if self.trace_configured.is_set() {"));
        assert!(wrapper.contains("TraceAlreadyConfigured"));
        assert!(wrapper.contains("path.to_str().ok_or("));
        assert!(wrapper.contains("TracePathNotUtf8"));
        assert!(wrapper.contains("self.trace_configured = TraceFlag::new(true);"));
        assert!(wrapper.contains("TraceOpenFailed"));
        assert!(wrapper.contains("self.evaluated = TraceFlag::new(true);"));
        assert!(
            wrapper
                .contains("self.trace_open = TraceFlag::new(self.inner_ref()?.trace_is_open());")
        );
        assert!(wrapper.contains(
            "if self.finished {\n            self.trace_open = TraceFlag::new(false);\n            return Ok(());"
        ));
        assert!(wrapper.contains("self.inner_mut()?.close_trace();"));
        assert!(wrapper.contains("self.trace_open = TraceFlag::new(false);"));
        assert!(wrapper.contains("pub const fn trace_is_open(&self) -> bool {"));
        assert!(wrapper.contains("if self.finished {\n            return Ok(());\n        }"));
        assert!(wrapper.contains("self.inner_mut()?.finish();"));
        assert!(wrapper.contains(
            "if let Some(inner) = self.inner.as_mut() {\n            inner.finish();\n        }"
        ));
        assert!(wrapper.contains("#[allow(clippy::same_name_method)]"));
        assert!(wrapper.contains("impl ::vvm::__private::TraceableDut for Counter"));
        assert!(bridge.contains("fn trace_is_open(self: &Counter) -> bool;"));

        Ok(())
    }

    #[test]
    fn wide_codegen_generates_slice_based_artifacts() -> Result<(), Box<dyn std::error::Error>> {
        let metadata = wide_ports_metadata()?;
        let output = tempdir()?;
        let generated = generate(&metadata, "Vwide_ports", output.path(), None, false)?;

        let header = std::fs::read_to_string(&generated.cpp_header)?;
        let source = std::fs::read_to_string(&generated.cpp_source)?;
        let bridge = std::fs::read_to_string(&generated.cxx_bridge)?;
        let wrapper = std::fs::read_to_string(&generated.rust_wrapper)?;

        assert_wide_header_artifacts(&header);

        assert_wide_source_artifacts(&source);

        assert_wide_bridge_artifacts(&bridge);

        assert_wide_wrapper_artifacts(&wrapper);

        assert_contract_fixture("wide_ports.txt", &header, &source, &bridge, &wrapper)?;

        Ok(())
    }

    #[test]
    fn packed_array_codegen_generates_newtypes_and_flattened_transfer()
    -> Result<(), Box<dyn std::error::Error>> {
        let metadata = packed_array_ports_metadata()?;
        let output = tempdir()?;
        let generated = generate(&metadata, "Vpacked_array_ports", output.path(), None, false)?;

        let header = std::fs::read_to_string(&generated.cpp_header)?;
        let source = std::fs::read_to_string(&generated.cpp_source)?;
        let bridge = std::fs::read_to_string(&generated.cxx_bridge)?;
        let wrapper = std::fs::read_to_string(&generated.rust_wrapper)?;

        assert!(header.contains("void set_packed_bytes(std::uint32_t value) noexcept;"));
        assert!(header.contains("[[nodiscard]] std::uint32_t packed_bytes_out() const noexcept;"));
        assert!(header.contains("[[nodiscard]] std::uint8_t first_byte() const noexcept;"));
        assert!(header.contains("[[nodiscard]] std::uint8_t last_byte() const noexcept;"));
        assert!(!header.contains("rust::Slice<const std::uint32_t> words) noexcept;"));

        assert!(source.contains("PackedArrayPorts::set_packed_bytes("));
        assert!(source.contains("PackedArrayPorts::packed_bytes_out() const noexcept"));

        assert!(
            bridge.contains("fn set_packed_bytes(self: Pin<&mut PackedArrayPorts>, value: u32);")
        );
        assert!(bridge.contains("fn packed_bytes_out(self: &PackedArrayPorts) -> u32;"));

        assert!(wrapper.contains("pub struct PackedBytes {"));
        assert!(wrapper.contains("pub struct PackedBytesOut {"));
        assert!(wrapper.contains("impl ::vvm::__private::PackedValue for PackedBytes {"));
        assert!(wrapper.contains("pub const WIDTH: usize = 32;"));
        assert!(wrapper.contains("pub const LEN: usize = 4;"));
        assert!(wrapper.contains("pub const ELEMENT_WIDTH: usize = 8;"));
        assert!(wrapper.contains("pub const LEFT: i64 = 3;"));
        assert!(wrapper.contains("pub const RIGHT: i64 = 0;"));
        assert!(wrapper.contains("pub fn element(&self, index: i64)"));
        assert!(wrapper.contains("pub fn set_element(&mut self, index: i64, value: u8)"));
        assert!(wrapper.contains("Borrow<PackedBytes>"));
        assert!(wrapper.contains("Result<PackedBytesOut>"));
        assert!(wrapper.contains("PackedLayoutFailed"));
        assert!(wrapper.contains("::vvm::__private::extract_unsigned"));
        assert!(wrapper.contains("::vvm::__private::insert_unsigned"));
        assert!(wrapper.contains("::vvm::__private::PackedLayoutError::range_out_of_bounds("));
        assert!(wrapper.contains("::vvm::__private::PackedLayoutError::invalid_packed_value"));
        assert!(wrapper.contains("let raw = ::vvm::__private::extract_unsigned("));
        assert!(wrapper.contains("let raw: u32 = u32::try_from(raw)"));
        assert!(wrapper.contains("let bits = ::vvm::__private::Bits::<32>::from("));
        assert!(wrapper.contains("Ok(PackedBytesOut::from_bits(bits))"));

        Ok(())
    }

    #[test]
    fn unpacked_array_codegen_uses_element_slices() -> Result<(), Box<dyn std::error::Error>> {
        let output = tempdir()?;
        let generated = generate(
            &unpacked_array_ports_metadata()?,
            "Vunpacked_array_ports",
            output.path(),
            None,
            false,
        )?;
        let header = std::fs::read_to_string(&generated.cpp_header)?;
        let bridge = std::fs::read_to_string(&generated.cxx_bridge)?;
        let wrapper = std::fs::read_to_string(&generated.rust_wrapper)?;
        assert!(header.contains("rust::Slice<const std::uint8_t> values"));
        assert!(header.contains("rust::Slice<const std::int16_t> values"));
        assert!(header.contains("rust::Slice<const std::uint32_t> words"));
        assert!(bridge.contains("values: &[u8]"));
        assert!(bridge.contains("values: &[i16]"));
        assert!(bridge.contains("words: &[u32]"));
        assert!(wrapper.contains("pub struct Flags"));
        assert!(wrapper.contains("elements: [bool; 4]"));
        assert!(wrapper.contains("elements: [::vvm::__private::Bits<129>; 2]"));
        assert!(wrapper.contains("UnpackedArrayTransferFailed"));
        Ok(())
    }

    #[test]
    fn packed_struct_codegen_generates_newtypes_and_flattened_transfer()
    -> Result<(), Box<dyn std::error::Error>> {
        let metadata = packed_struct_ports_metadata()?;
        let output = tempdir()?;
        let generated = generate(
            &metadata,
            "Vpacked_struct_ports",
            output.path(),
            None,
            false,
        )?;

        let header = std::fs::read_to_string(&generated.cpp_header)?;
        let bridge = std::fs::read_to_string(&generated.cxx_bridge)?;
        let wrapper = std::fs::read_to_string(&generated.rust_wrapper)?;

        assert!(header.contains("void set_packet(std::uint32_t value) noexcept;"));
        assert!(header.contains("[[nodiscard]] std::uint32_t packet_out() const noexcept;"));
        assert!(
            header
                .contains("bool set_wide_packet(rust::Slice<const std::uint32_t> words) noexcept;")
        );
        assert!(
            header
                .contains("bool wide_packet_out(rust::Slice<std::uint32_t> words) const noexcept;")
        );

        assert!(bridge.contains("fn set_packet(self: Pin<&mut PackedStructPorts>, value: u32);"));
        assert!(bridge.contains("fn packet_out(self: &PackedStructPorts) -> u32;"));
        assert!(bridge.contains(
            "fn set_wide_packet(self: Pin<&mut PackedStructPorts>, words: &[u32]) -> bool;"
        ));
        assert!(
            bridge.contains(
                "fn wide_packet_out(self: &PackedStructPorts, words: &mut [u32]) -> bool;"
            )
        );

        assert!(wrapper.contains("pub struct Packet {"));
        assert!(wrapper.contains("pub struct PacketOut {"));
        assert!(wrapper.contains("pub struct WidePacket {"));
        assert!(wrapper.contains("pub struct WidePacketOut {"));
        assert!(
            wrapper
                .contains("pub const FIELDS: &'static [::vvm::__private::PackedFieldLayout] = &[")
        );
        assert!(wrapper.contains("pub const LAYOUT: ::vvm::__private::PackedLayout ="));
        assert!(wrapper.contains(
            "pub fn opcode(&self) -> std::result::Result<u8, ::vvm::__private::PackedLayoutError> \
             {"
        ));
        assert!(wrapper.contains(
            "pub fn set_opcode(&mut self, value: u8) -> std::result::Result<(), \
             ::vvm::__private::PackedLayoutError> {"
        ));
        assert!(wrapper.contains(
            "pub fn valid(&self) -> std::result::Result<bool, \
             ::vvm::__private::PackedLayoutError> {"
        ));
        assert!(wrapper.contains(
            "pub fn set_valid(&mut self, value: bool) -> std::result::Result<(), \
             ::vvm::__private::PackedLayoutError> {"
        ));
        assert!(wrapper.contains(
            "pub fn delta(&self) -> std::result::Result<i8, ::vvm::__private::PackedLayoutError> {"
        ));
        assert!(wrapper.contains(
            "pub fn set_delta(&mut self, value: i8) -> std::result::Result<(), \
             ::vvm::__private::PackedLayoutError> {"
        ));
        assert!(wrapper.contains(
            "pub fn payload(&self) -> std::result::Result<u16, \
             ::vvm::__private::PackedLayoutError> {"
        ));
        assert!(wrapper.contains(
            "pub fn set_payload(&mut self, value: u16) -> std::result::Result<(), \
             ::vvm::__private::PackedLayoutError> {"
        ));
        assert!(wrapper.contains(
            "pub fn payload(&self) -> std::result::Result<::vvm::__private::SignedBits<129>, \
             ::vvm::__private::PackedLayoutError> {"
        ));
        assert!(wrapper.contains(
            "pub fn set_payload(&mut self, value: impl \
             ::core::borrow::Borrow<::vvm::__private::SignedBits<129>>) -> \
             std::result::Result<(), ::vvm::__private::PackedLayoutError> {"
        ));
        assert!(wrapper.contains("::vvm::__private::extract_unsigned"));
        assert!(wrapper.contains("::vvm::__private::insert_unsigned"));
        assert!(wrapper.contains("::vvm::__private::extract_signed"));
        assert!(wrapper.contains("::vvm::__private::insert_signed"));
        assert!(
            wrapper
                .contains("::vvm::__private::extract_packed::<::vvm::__private::SignedBits<129>>(")
        );
        assert!(wrapper.contains("::vvm::__private::insert_packed("));
        assert!(wrapper.contains("impl ::vvm::__private::PackedValue for Packet {"));
        assert!(wrapper.contains("value: impl ::core::borrow::Borrow<Packet>"));
        assert!(wrapper.contains("pub fn packet_out(&self) -> Result<PacketOut> {"));
        assert!(wrapper.contains("PackedLayoutFailed"));

        assert_contract_fixture("packed_struct_ports.txt", &header, "", &bridge, &wrapper)?;

        Ok(())
    }

    #[test]
    fn multi_clock_like_ports_generate_independent_scalar_accessors()
    -> Result<(), Box<dyn std::error::Error>> {
        let width = BitWidth::new(NonZeroU32::MIN);
        let metadata = DutMetadata {
            name: String::from("multi_clock_counter"),
            top_module: String::from("multi_clock_counter"),
            ports: vec![
                scalar_port("core_clk", PortDirection::Input, width, false),
                scalar_port("peripheral_clk", PortDirection::Input, width, false),
                scalar_port("reset_n", PortDirection::Input, width, false),
                scalar_port("peripheral_enable", PortDirection::Input, width, false),
                scalar_port("core_sample", PortDirection::Output, width, false),
                scalar_port("peripheral_count", PortDirection::Output, width, false),
            ],
        };
        let output = tempdir()?;
        let generated = generate(
            &metadata,
            "Vmulti_clock_counter",
            output.path(),
            None,
            false,
        )?;
        let header = std::fs::read_to_string(&generated.cpp_header)?;
        let source = std::fs::read_to_string(&generated.cpp_source)?;
        let bridge = std::fs::read_to_string(&generated.cxx_bridge)?;
        let wrapper = std::fs::read_to_string(&generated.rust_wrapper)?;

        assert_contract_fixture("multi_clock_ports.txt", &header, &source, &bridge, &wrapper)?;

        Ok(())
    }

    #[test]
    fn packed_enum_codegen_generates_wrappers_and_flattened_transfer()
    -> Result<(), Box<dyn std::error::Error>> {
        let metadata = packed_enum_ports_metadata()?;
        let output = tempdir()?;
        let generated = generate(&metadata, "Vpacked_enum_ports", output.path(), None, false)?;
        let expected_directory = expected_codegen_directory("packed-enum-ports");

        assert_generated_artifacts_match(&generated, &expected_directory, "packed_enum_ports")?;

        let header = std::fs::read_to_string(&generated.cpp_header)?;
        let bridge = std::fs::read_to_string(&generated.cxx_bridge)?;
        let wrapper = std::fs::read_to_string(&generated.rust_wrapper)?;

        assert!(header.contains("void set_state(std::uint8_t value) noexcept;"));
        assert!(header.contains("[[nodiscard]] std::uint8_t state_out() const noexcept;"));
        assert!(header.contains("void set_signed_state(std::int8_t value) noexcept;"));
        assert!(header.contains("[[nodiscard]] std::int8_t signed_state_out() const noexcept;"));

        assert!(bridge.contains("fn set_state(self: Pin<&mut PackedEnumPorts>, value: u8);"));
        assert!(bridge.contains("fn state_out(self: &PackedEnumPorts) -> u8;"));
        assert!(
            bridge.contains("fn set_signed_state(self: Pin<&mut PackedEnumPorts>, value: i8);")
        );
        assert!(bridge.contains("fn signed_state_out(self: &PackedEnumPorts) -> i8;"));

        assert!(wrapper.contains("pub struct State {"));
        assert!(wrapper.contains("pub enum StateVariant {"));
        assert!(wrapper.contains("STATE_IDLE"));
        assert!(wrapper.contains("STATE_BUSY"));
        assert!(wrapper.contains("STATE_DONE"));
        assert!(wrapper.contains("STATE_ERROR"));
        assert!(wrapper.contains(
            "pub const VARIANTS: &'static [::vvm::__private::PackedEnumVariantLayout] = &["
        ));
        assert!(wrapper.contains("pub const LAYOUT: ::vvm::__private::PackedEnumLayout ="));
        assert!(wrapper.contains("pub fn from_raw(value: u64) -> Self {"));
        assert!(wrapper.contains(
            "pub fn raw(&self) -> std::result::Result<u64, ::vvm::__private::PackedLayoutError> {"
        ));
        assert!(wrapper.contains("pub fn from_variant(variant: StateVariant) -> Self {"));
        assert!(wrapper.contains(
            "pub fn variant(&self) -> std::result::Result<Option<StateVariant>, \
             ::vvm::__private::PackedLayoutError> {"
        ));
        assert!(wrapper.contains(
            "pub fn name(&self) -> std::result::Result<Option<&'static str>, \
             ::vvm::__private::PackedLayoutError> {"
        ));
        assert!(wrapper.contains(
            "pub fn is_known(&self) -> std::result::Result<bool, \
             ::vvm::__private::PackedLayoutError> {"
        ));
        assert!(wrapper.contains("impl From<StateVariant> for State {"));
        assert!(wrapper.contains("impl ::vvm::__private::PackedValue for State {"));
        assert!(wrapper.contains("value: impl ::core::borrow::Borrow<State>"));
        assert!(wrapper.contains("pub fn state_out(&self) -> Result<StateOut> {"));
        assert!(wrapper.contains("PackedLayoutFailed"));
        assert!(wrapper.contains("pub struct SignedState {"));
        assert!(wrapper.contains("pub enum SignedStateVariant {"));
        assert!(wrapper.contains("SIGNED_NEG"));
        assert!(wrapper.contains("SIGNED_ZERO"));
        assert!(wrapper.contains("SIGNED_POS"));

        Ok(())
    }

    #[test]
    fn preserves_metadata_port_order() -> Result<(), Box<dyn std::error::Error>> {
        let width = BitWidth::new(NonZeroU32::MIN);

        let metadata = DutMetadata {
            name: "ordered".to_owned(),
            top_module: "ordered".to_owned(),
            ports: vec![
                scalar_port("z_input", PortDirection::Input, width, false),
                scalar_port("a_input", PortDirection::Input, width, false),
                scalar_port("m_output", PortDirection::Output, width, false),
            ],
        };

        let output = tempdir()?;
        let generated = generate(&metadata, "Vordered", output.path(), None, false)?;

        let header = std::fs::read_to_string(generated.cpp_header)?;

        let z_position = header.find("set_z_input").ok_or_else(|| {
            std::io::Error::new(std::io::ErrorKind::InvalidData, "missing set_z_input")
        })?;

        let a_position = header.find("set_a_input").ok_or_else(|| {
            std::io::Error::new(std::io::ErrorKind::InvalidData, "missing set_a_input")
        })?;

        let m_position = header.find("m_output").ok_or_else(|| {
            std::io::Error::new(std::io::ErrorKind::InvalidData, "missing m_output")
        })?;

        assert!(z_position < a_position);
        assert!(a_position < m_position);

        Ok(())
    }
}
