/// C++ adapter source generation.
pub mod cpp_adapter;
/// Raw CXX bridge source generation.
pub mod cxx_bridge;
/// Deterministic generated C++ naming.
pub mod names;
/// Safe Rust DUT wrapper generation.
pub mod rust_wrapper;
/// Generated signal type selection.
pub mod types;
/// Deterministic generated-file writing.
pub mod writer;

use std::fs;
use std::path::{Path, PathBuf};

use crate::metadata::DutMetadata;
use crate::{BuildError, BuildResult, TraceOptions};

/// Deterministic notice placed at the beginning of generated source files.
const GENERATED_NOTICE: &str = "// @generated by vvm-build. Do not edit.";

/// Generated DUT integration artifacts
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedArtifacts {
    /// Directory containing the generated public header.
    pub(crate) include_dir: PathBuf,

    /// Generated C++ adapter header.
    pub(crate) cpp_header: PathBuf,

    /// Generated C++ adapter source.
    pub(crate) cpp_source: PathBuf,

    /// Generated raw CXX bridge.
    pub(crate) cxx_bridge: PathBuf,

    /// Generated safe Rust DUT wrapper.
    pub(crate) rust_wrapper: PathBuf,
}

/// Generates the C++ adapter for one normalized DUT.
///
/// # Errors
///
/// Returns an error when generated names are invalid or output files cannot
/// be created.
pub fn generate(
    metadata: &DutMetadata,
    model_prefix: &str,
    output_dir: &Path,
    trace: Option<TraceOptions>,
) -> BuildResult<GeneratedArtifacts> {
    let names = names::resolve(metadata, model_prefix)?;
    let adapter = cpp_adapter::render(metadata, &names, trace);
    let bridge = cxx_bridge::render(metadata, &names, trace);
    let wrapper = rust_wrapper::render(metadata, &names, trace);

    fs::create_dir_all(output_dir).map_err(|source| BuildError::Io {
        operation: "create generated source directory",
        path: output_dir.to_path_buf(),
        source,
    })?;

    let cpp_header = output_dir.join(format!("{}.hpp", names.file_stem));
    let cpp_source = output_dir.join(format!("{}.cpp", names.file_stem));
    let cxx_bridge = output_dir.join("bridge.rs");
    let rust_wrapper = output_dir.join("dut.rs");

    writer::write_if_changed(&cpp_header, &adapter.header)?;
    writer::write_if_changed(&cpp_source, &adapter.source)?;
    writer::write_if_changed(&cxx_bridge, &bridge)?;
    writer::write_if_changed(&rust_wrapper, &wrapper)?;

    Ok(GeneratedArtifacts {
        include_dir: output_dir.to_path_buf(),
        cpp_header,
        cpp_source,
        cxx_bridge,
        rust_wrapper,
    })
}

#[cfg(test)]
mod tests {
    use std::num::NonZeroU32;
    use std::path::{Path, PathBuf};

    use tempfile::tempdir;

    use super::generate;
    use crate::TraceOptions;
    use crate::metadata::{
        BitWidth, DutMetadata, PackedScalarShape, Port, PortDirection, PortShape, RawMetadata,
        normalize,
    };
    use crate::verilator::VerilatorVersion;

    fn wide_ports_metadata() -> Result<DutMetadata, Box<dyn std::error::Error>> {
        let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));

        let metadata_fixture = manifest
            .join("tests")
            .join("fixtures")
            .join("verilator")
            .join("5.048")
            .join("wide_ports");

        let raw = RawMetadata::from_paths(
            VerilatorVersion::new(5, 48),
            &metadata_fixture.join("wide_ports.tree.json"),
            &metadata_fixture.join("wide_ports.tree.meta.json"),
        )?;

        Ok(normalize("wide_ports", "wide_ports", &raw)?)
    }

    fn counter_metadata() -> Result<crate::metadata::DutMetadata, Box<dyn std::error::Error>> {
        let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));

        let metadata_fixture = manifest
            .join("tests")
            .join("fixtures")
            .join("verilator")
            .join("5.048")
            .join("counter");

        let raw = RawMetadata::from_paths(
            VerilatorVersion::new(5, 48),
            &metadata_fixture.join("counter.tree.json"),
            &metadata_fixture.join("counter.tree.meta.json"),
        )?;

        Ok(normalize("counter", "counter", &raw)?)
    }

    fn signed_ports_metadata() -> Result<crate::metadata::DutMetadata, Box<dyn std::error::Error>> {
        let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));

        let metadata_fixture = manifest
            .join("tests")
            .join("fixtures")
            .join("verilator")
            .join("5.048")
            .join("signed_ports");

        let raw = RawMetadata::from_paths(
            VerilatorVersion::new(5, 48),
            &metadata_fixture.join("signed_ports.tree.json"),
            &metadata_fixture.join("signed_ports.tree.meta.json"),
        )?;

        Ok(normalize("signed_ports", "signed_ports", &raw)?)
    }

    fn packed_array_ports_metadata()
    -> Result<crate::metadata::DutMetadata, Box<dyn std::error::Error>> {
        let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));

        let metadata_fixture = manifest
            .join("tests")
            .join("fixtures")
            .join("verilator")
            .join("5.048")
            .join("packed_array_ports");

        let raw = RawMetadata::from_paths(
            VerilatorVersion::new(5, 48),
            &metadata_fixture.join("packed_array_ports.tree.json"),
            &metadata_fixture.join("packed_array_ports.tree.meta.json"),
        )?;

        Ok(normalize("packed_array_ports", "packed_array_ports", &raw)?)
    }

    fn packed_struct_ports_metadata()
    -> Result<crate::metadata::DutMetadata, Box<dyn std::error::Error>> {
        let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));

        let metadata_fixture = manifest
            .join("tests")
            .join("fixtures")
            .join("verilator")
            .join("5.048")
            .join("packed_struct_ports");

        let raw = RawMetadata::from_paths(
            VerilatorVersion::new(5, 48),
            &metadata_fixture.join("packed_struct_ports.tree.json"),
            &metadata_fixture.join("packed_struct_ports.tree.meta.json"),
        )?;

        Ok(normalize(
            "packed_struct_ports",
            "packed_struct_ports",
            &raw,
        )?)
    }

    fn expected_codegen_directory(name: &str) -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("tests")
            .join("fixtures")
            .join("codegen")
            .join(name)
    }

    fn assert_generated_artifacts_match(
        generated: &super::GeneratedArtifacts,
        expected_directory: &Path,
        file_stem: &str,
    ) -> Result<(), Box<dyn std::error::Error>> {
        assert_generated_snapshot(
            &generated.cpp_header,
            &expected_directory.join(format!("{file_stem}.hpp")),
        )?;
        assert_generated_snapshot(
            &generated.cpp_source,
            &expected_directory.join(format!("{file_stem}.cpp")),
        )?;
        assert_generated_snapshot(&generated.cxx_bridge, &expected_directory.join("bridge.rs"))?;
        assert_generated_snapshot(&generated.rust_wrapper, &expected_directory.join("dut.rs"))?;

        Ok(())
    }

    fn assert_same_generated_contents(
        first: &super::GeneratedArtifacts,
        second: &super::GeneratedArtifacts,
    ) -> Result<(), Box<dyn std::error::Error>> {
        assert_eq!(
            std::fs::read_to_string(&first.cpp_header)?,
            std::fs::read_to_string(&second.cpp_header)?
        );
        assert_eq!(
            std::fs::read_to_string(&first.cpp_source)?,
            std::fs::read_to_string(&second.cpp_source)?
        );
        assert_eq!(
            std::fs::read_to_string(&first.cxx_bridge)?,
            std::fs::read_to_string(&second.cxx_bridge)?
        );
        assert_eq!(
            std::fs::read_to_string(&first.rust_wrapper)?,
            std::fs::read_to_string(&second.rust_wrapper)?
        );

        Ok(())
    }

    fn assert_generated_snapshot(
        actual_path: &Path,
        expected_path: &Path,
    ) -> Result<(), Box<dyn std::error::Error>> {
        let actual = std::fs::read_to_string(actual_path)?;
        let expected = std::fs::read_to_string(expected_path)?;

        assert_eq!(
            actual,
            expected,
            "generated artifact `{}` differs from its snapshot",
            actual_path.display()
        );

        assert!(
            actual.ends_with('\n'),
            "generated artifact must end with a newline: {}",
            actual_path.display()
        );

        assert!(
            !actual.contains('\r'),
            "generated artifact must use Unix newlines: {}",
            actual_path.display()
        );

        assert!(
            !actual.contains(env!("CARGO_MANIFEST_DIR")),
            "generated artifact contains a host checkout path: {}",
            actual_path.display()
        );

        Ok(())
    }

    fn scalar_port(name: &str, direction: PortDirection, width: BitWidth, signed: bool) -> Port {
        Port {
            name: name.to_owned(),
            direction,
            width,
            signed,
            shape: PortShape::PackedScalar(PackedScalarShape { width, signed }),
        }
    }

    #[test]
    fn generates_expected_counter_artifacts() -> Result<(), Box<dyn std::error::Error>> {
        let metadata = counter_metadata()?;
        let output = tempdir()?;
        let generated = generate(&metadata, "Vcounter", output.path(), None)?;
        let expected_directory = expected_codegen_directory("counter");

        assert_generated_artifacts_match(&generated, &expected_directory, "counter")?;

        let header = std::fs::read_to_string(&generated.cpp_header)?;
        let source = std::fs::read_to_string(&generated.cpp_source)?;
        let bridge = std::fs::read_to_string(&generated.cxx_bridge)?;
        let wrapper = std::fs::read_to_string(&generated.rust_wrapper)?;

        assert!(!header.contains("rust/cxx.h"));
        assert!(!header.contains("open_trace"));
        assert!(!source.contains("VerilatedVcdC"));
        assert!(!source.contains("traceEverOn"));
        assert!(!bridge.contains("open_trace"));
        assert!(!wrapper.contains("TraceAfterEvaluation"));
        assert!(!wrapper.contains("TraceableDut"));
        assert!(!wrapper.contains(".pin_mut()"));
        assert!(!wrapper.contains("unsafe"));
        assert!(!wrapper.contains("Vcounter"));
        assert!(wrapper.contains("pub enum CounterError"));
        assert!(wrapper.contains("impl ::vvm::Dut for Counter"));
        assert!(wrapper.contains("impl Drop for Counter"));
        assert!(wrapper.contains("impl std::fmt::Debug for Counter"));

        Ok(())
    }

    #[test]
    fn generates_signed_port_artifacts_from_fixture() -> Result<(), Box<dyn std::error::Error>> {
        let metadata = signed_ports_metadata()?;
        let output = tempdir()?;
        let generated = generate(&metadata, "Vsigned_ports", output.path(), None)?;

        let header = std::fs::read_to_string(&generated.cpp_header)?;
        let source = std::fs::read_to_string(&generated.cpp_source)?;
        let bridge = std::fs::read_to_string(&generated.cxx_bridge)?;
        let wrapper = std::fs::read_to_string(&generated.rust_wrapper)?;

        assert!(header.contains("void set_input_i1(std::int8_t value) noexcept;"));
        assert!(header.contains("void set_input_i5(std::int8_t value) noexcept;"));
        assert!(header.contains("void set_input_i9(std::int16_t value) noexcept;"));
        assert!(header.contains("void set_input_i17(std::int32_t value) noexcept;"));
        assert!(header.contains("void set_input_i33(std::int64_t value) noexcept;"));
        assert!(header.contains("void set_input_i64(std::int64_t value) noexcept;"));
        assert!(header.contains("std::int8_t output_i1() const noexcept;"));
        assert!(header.contains("std::int64_t output_i64() const noexcept;"));

        assert!(source.contains("    }\n\n    template <typename Signed,"));
        assert!(source.contains("using UnsignedType = std::uint8_t;"));
        assert!(source.contains("using UnsignedType = std::uint16_t;"));
        assert!(source.contains("using UnsignedType = std::uint32_t;"));
        assert!(source.contains("using UnsignedType = std::uint64_t;"));
        assert!(source.contains("static_cast<std::uint8_t>(0x1FULL)"));
        assert!(source.contains("Impl::sign_extend<std::int8_t, 1>("));
        assert!(source.contains("Impl::sign_extend<std::int8_t, 5>("));
        assert!(source.contains("Impl::sign_extend<std::int16_t, 9>("));
        assert!(source.contains("Impl::sign_extend<std::int32_t, 17>("));
        assert!(source.contains("Impl::sign_extend<std::int64_t, 33>("));
        assert!(source.contains("Impl::sign_extend<std::int64_t, 64>("));

        assert!(bridge.contains("fn set_input_i1(self: Pin<&mut SignedPorts>, value: i8);"));
        assert!(bridge.contains("fn set_input_i9(self: Pin<&mut SignedPorts>, value: i16);"));
        assert!(bridge.contains("fn set_input_i17(self: Pin<&mut SignedPorts>, value: i32);"));
        assert!(bridge.contains("fn set_input_i33(self: Pin<&mut SignedPorts>, value: i64);"));
        assert!(bridge.contains("fn output_i1(self: &SignedPorts) -> i8;"));
        assert!(bridge.contains("fn output_i64(self: &SignedPorts) -> i64;"));

        assert!(wrapper.contains("value: impl ::core::borrow::Borrow<i8>"));
        assert!(wrapper.contains("value: impl ::core::borrow::Borrow<i16>"));
        assert!(wrapper.contains("value: impl ::core::borrow::Borrow<i32>"));
        assert!(wrapper.contains("value: impl ::core::borrow::Borrow<i64>"));
        assert!(wrapper.contains("*::core::borrow::Borrow::borrow(&value)"));
        assert!(wrapper.contains("pub fn output_i1(&self) -> Result<i8> {"));
        assert!(wrapper.contains("pub fn output_i64(&self) -> Result<i64> {"));

        Ok(())
    }

    #[test]
    fn generates_expected_traced_counter_artifacts() -> Result<(), Box<dyn std::error::Error>> {
        let metadata = counter_metadata()?;
        let output = tempdir()?;
        let generated = generate(
            &metadata,
            "Vcounter",
            output.path(),
            Some(TraceOptions::vcd()),
        )?;
        let expected_directory = expected_codegen_directory("counter-vcd");

        assert_generated_artifacts_match(&generated, &expected_directory, "counter")?;

        let header = std::fs::read_to_string(&generated.cpp_header)?;
        let source = std::fs::read_to_string(&generated.cpp_source)?;
        let bridge = std::fs::read_to_string(&generated.cxx_bridge)?;
        let wrapper = std::fs::read_to_string(&generated.rust_wrapper)?;

        assert!(header.contains("rust/cxx.h"));
        assert!(header.contains("open_trace"));
        assert!(header.contains("close_trace"));
        assert!(header.contains("trace_is_open"));
        assert!(!header.contains("VerilatedVcdC"));
        assert!(source.contains("context->traceEverOn(true)"));
        assert!(source.contains("std::unique_ptr<VerilatedVcdC>"));
        assert!(source.contains("impl_->model->trace(impl_->trace.get(), 99);"));
        assert!(source.contains("trace->dump"));
        assert!(source.contains("trace->flush"));
        assert!(source.contains("trace->close"));
        assert!(source.contains("last_trace_time"));
        assert!(source.contains("has_trace_dump"));
        assert!(bridge.contains("fn open_trace"));
        assert!(bridge.contains("fn close_trace"));
        assert!(bridge.contains("fn trace_is_open"));
        assert!(bridge.contains("path: &str"));
        assert!(wrapper.contains("TraceAfterEvaluation"));
        assert!(wrapper.contains("TraceAlreadyConfigured"));
        assert!(wrapper.contains("TracePathNotUtf8"));
        assert!(wrapper.contains("TraceOpenFailed"));
        assert!(wrapper.contains("evaluated"));
        assert!(wrapper.contains("trace_configured"));
        assert!(wrapper.contains("trace_open"));
        assert!(wrapper.contains("impl ::vvm::TraceableDut"));
        assert!(wrapper.contains("impl ::vvm::Dut"));
        assert!(wrapper.contains("SimulationTime"));
        assert!(wrapper.contains("advance_time"));
        assert!(wrapper.contains("Drop"));

        let trace_ever_on = source.find("context->traceEverOn(true)").ok_or_else(|| {
            std::io::Error::new(std::io::ErrorKind::InvalidData, "missing traceEverOn")
        })?;
        let model_construction = source
            .find("model = std::make_unique<Vcounter>(context.get());")
            .ok_or_else(|| {
                std::io::Error::new(
                    std::io::ErrorKind::InvalidData,
                    "missing traced model construction",
                )
            })?;

        assert!(trace_ever_on < model_construction);

        Ok(())
    }

    #[test]
    fn generates_deterministic_output() -> Result<(), Box<dyn std::error::Error>> {
        let metadata = counter_metadata()?;

        let first_output = tempdir()?;
        let second_output = tempdir()?;
        let traced_first_output = tempdir()?;
        let traced_second_output = tempdir()?;

        let first = generate(&metadata, "Vcounter", first_output.path(), None)?;
        let second = generate(&metadata, "Vcounter", second_output.path(), None)?;
        let traced_first = generate(
            &metadata,
            "Vcounter",
            traced_first_output.path(),
            Some(TraceOptions::vcd()),
        )?;
        let traced_second = generate(
            &metadata,
            "Vcounter",
            traced_second_output.path(),
            Some(TraceOptions::vcd()),
        )?;

        assert_same_generated_contents(&first, &second)?;
        assert_same_generated_contents(&traced_first, &traced_second)?;

        Ok(())
    }

    #[test]
    fn traced_wrapper_generation_encodes_trace_lifecycle_rules()
    -> Result<(), Box<dyn std::error::Error>> {
        let metadata = counter_metadata()?;
        let output = tempdir()?;
        let generated = generate(
            &metadata,
            "Vcounter",
            output.path(),
            Some(TraceOptions::vcd()),
        )?;

        let bridge = std::fs::read_to_string(&generated.cxx_bridge)?;
        let wrapper = std::fs::read_to_string(&generated.rust_wrapper)?;

        assert!(wrapper.contains("if self.evaluated.is_set() {"));
        assert!(wrapper.contains("TraceAfterEvaluation"));
        assert!(wrapper.contains("if self.trace_configured.is_set() {"));
        assert!(wrapper.contains("TraceAlreadyConfigured"));
        assert!(wrapper.contains("path.to_str().ok_or("));
        assert!(wrapper.contains("TracePathNotUtf8"));
        assert!(wrapper.contains("self.trace_configured = TraceFlag::new(true);"));
        assert!(wrapper.contains("TraceOpenFailed"));
        assert!(wrapper.contains("self.evaluated = TraceFlag::new(true);"));
        assert!(
            wrapper
                .contains("self.trace_open = TraceFlag::new(self.inner_ref()?.trace_is_open());")
        );
        assert!(wrapper.contains(
            "if self.finished {\n            self.trace_open = TraceFlag::new(false);\n            return Ok(());"
        ));
        assert!(wrapper.contains("self.inner_mut()?.close_trace();"));
        assert!(wrapper.contains("self.trace_open = TraceFlag::new(false);"));
        assert!(wrapper.contains("pub const fn trace_is_open(&self) -> bool {"));
        assert!(wrapper.contains("if self.finished {\n            return Ok(());\n        }"));
        assert!(wrapper.contains("self.inner_mut()?.finish();"));
        assert!(wrapper.contains(
            "if let Some(inner) = self.inner.as_mut() {\n            inner.finish();\n        }"
        ));
        assert!(wrapper.contains("#[allow(clippy::same_name_method)]"));
        assert!(wrapper.contains("impl ::vvm::TraceableDut for Counter"));
        assert!(bridge.contains("fn trace_is_open(self: &Counter) -> bool;"));

        Ok(())
    }

    #[test]
    #[allow(clippy::too_many_lines)]
    fn wide_codegen_generates_slice_based_artifacts() -> Result<(), Box<dyn std::error::Error>> {
        let metadata = wide_ports_metadata()?;
        let output = tempdir()?;
        let generated = generate(&metadata, "Vwide_ports", output.path(), None)?;

        let header = std::fs::read_to_string(&generated.cpp_header)?;
        let source = std::fs::read_to_string(&generated.cpp_source)?;
        let bridge = std::fs::read_to_string(&generated.cxx_bridge)?;
        let wrapper = std::fs::read_to_string(&generated.rust_wrapper)?;

        assert!(header.contains("#include \"rust/cxx.h\""));
        assert!(
            header.contains("bool set_input_u65(rust::Slice<const std::uint32_t> words) noexcept;")
        );
        assert!(
            header.contains("bool set_input_u96(rust::Slice<const std::uint32_t> words) noexcept;")
        );
        assert!(
            header
                .contains("bool set_input_u129(rust::Slice<const std::uint32_t> words) noexcept;")
        );
        assert!(
            header
                .contains("bool set_input_u256(rust::Slice<const std::uint32_t> words) noexcept;")
        );
        assert!(
            header.contains("bool set_input_i65(rust::Slice<const std::uint32_t> words) noexcept;")
        );
        assert!(
            header
                .contains("bool set_input_i129(rust::Slice<const std::uint32_t> words) noexcept;")
        );
        assert!(
            header.contains("bool output_u65(rust::Slice<std::uint32_t> words) const noexcept;")
        );
        assert!(
            header.contains("bool output_u96(rust::Slice<std::uint32_t> words) const noexcept;")
        );
        assert!(
            header.contains("bool output_u129(rust::Slice<std::uint32_t> words) const noexcept;")
        );
        assert!(
            header.contains("bool output_u256(rust::Slice<std::uint32_t> words) const noexcept;")
        );
        assert!(
            header.contains("bool output_i65(rust::Slice<std::uint32_t> words) const noexcept;")
        );
        assert!(
            header.contains("bool output_i129(rust::Slice<std::uint32_t> words) const noexcept;")
        );
        assert!(!header.contains("set_input_u65(std::uint64_t value) noexcept"));
        assert!(!header.contains("set_input_u96(std::uint64_t value) noexcept"));
        assert!(!header.contains("output_u96() const noexcept"));
        assert!(!header.contains("output_u256() const noexcept"));

        assert!(source.contains("constexpr std::size_t expected_words{3};"));
        assert!(source.contains("constexpr std::size_t expected_words{5};"));
        assert!(source.contains("constexpr std::size_t expected_words{8};"));
        assert!(source.contains("static_assert(RawType::Words == expected_words);"));
        assert!(source.contains("if (words.size() != expected_words) {"));
        assert!(source.contains("return false;"));
        assert!(source.contains("raw_value[index] = words[index];"));
        assert!(source.contains("words[index] = raw_value[index];"));
        assert!(source.contains("raw_value[2] &= 0x1U;"));
        assert!(source.contains("raw_value[4] &= 0x1U;"));
        assert!(source.contains("words[2] &= 0x1U;"));
        assert!(source.contains("words[4] &= 0x1U;"));
        assert!(!source.contains("raw_value[2] &= 0xFFFFFFFFU;"));
        assert!(!source.contains("words[2] &= 0xFFFFFFFFU;"));
        assert!(!source.contains("raw_value[7] &= 0xFFFFFFFFU;"));
        assert!(!source.contains("words[7] &= 0xFFFFFFFFU;"));

        assert!(
            bridge.contains("fn set_input_u65(self: Pin<&mut WidePorts>, words: &[u32]) -> bool;")
        );
        assert!(
            bridge.contains("fn set_input_u96(self: Pin<&mut WidePorts>, words: &[u32]) -> bool;")
        );
        assert!(
            bridge.contains("fn set_input_u129(self: Pin<&mut WidePorts>, words: &[u32]) -> bool;")
        );
        assert!(
            bridge.contains("fn set_input_u256(self: Pin<&mut WidePorts>, words: &[u32]) -> bool;")
        );
        assert!(
            bridge.contains("fn set_input_i65(self: Pin<&mut WidePorts>, words: &[u32]) -> bool;")
        );
        assert!(
            bridge.contains("fn set_input_i129(self: Pin<&mut WidePorts>, words: &[u32]) -> bool;")
        );
        assert!(bridge.contains("fn output_u65(self: &WidePorts, words: &mut [u32]) -> bool;"));
        assert!(bridge.contains("fn output_u96(self: &WidePorts, words: &mut [u32]) -> bool;"));
        assert!(bridge.contains("fn output_u129(self: &WidePorts, words: &mut [u32]) -> bool;"));
        assert!(bridge.contains("fn output_u256(self: &WidePorts, words: &mut [u32]) -> bool;"));
        assert!(bridge.contains("fn output_i65(self: &WidePorts, words: &mut [u32]) -> bool;"));
        assert!(bridge.contains("fn output_i129(self: &WidePorts, words: &mut [u32]) -> bool;"));

        assert!(wrapper.contains("value: impl ::core::borrow::Borrow<::vvm::Bits<65>>"));
        assert!(wrapper.contains("value: impl ::core::borrow::Borrow<::vvm::Bits<96>>"));
        assert!(wrapper.contains("value: impl ::core::borrow::Borrow<::vvm::Bits<129>>"));
        assert!(wrapper.contains("value: impl ::core::borrow::Borrow<::vvm::Bits<256>>"));
        assert!(wrapper.contains("value: impl ::core::borrow::Borrow<::vvm::SignedBits<65>>"));
        assert!(wrapper.contains("value: impl ::core::borrow::Borrow<::vvm::SignedBits<129>>"));
        assert!(wrapper.contains("pub fn output_u65(&self) -> Result<::vvm::Bits<65>> {"));
        assert!(wrapper.contains("pub fn output_u96(&self) -> Result<::vvm::Bits<96>> {"));
        assert!(wrapper.contains("pub fn output_u129(&self) -> Result<::vvm::Bits<129>> {"));
        assert!(wrapper.contains("pub fn output_u256(&self) -> Result<::vvm::Bits<256>> {"));
        assert!(wrapper.contains("pub fn output_i65(&self) -> Result<::vvm::SignedBits<65>> {"));
        assert!(wrapper.contains("pub fn output_i129(&self) -> Result<::vvm::SignedBits<129>> {"));
        assert!(wrapper.contains("vec![0_u32; ::vvm::Bits::<65>::WORDS];"));
        assert!(wrapper.contains("vec![0_u32; ::vvm::Bits::<96>::WORDS];"));
        assert!(wrapper.contains("vec![0_u32; ::vvm::Bits::<129>::WORDS];"));
        assert!(wrapper.contains("vec![0_u32; ::vvm::Bits::<256>::WORDS];"));
        assert!(wrapper.contains("vec![0_u32; ::vvm::SignedBits::<65>::WORDS];"));
        assert!(wrapper.contains("vec![0_u32; ::vvm::SignedBits::<129>::WORDS];"));
        assert!(wrapper.contains("WidePortTransferFailed"));
        assert!(wrapper.contains(".map_err(|_error| {"));

        Ok(())
    }

    #[test]
    #[allow(clippy::too_many_lines)]
    fn packed_array_codegen_generates_newtypes_and_flattened_transfer()
    -> Result<(), Box<dyn std::error::Error>> {
        let metadata = packed_array_ports_metadata()?;
        let output = tempdir()?;
        let generated = generate(&metadata, "Vpacked_array_ports", output.path(), None)?;

        let header = std::fs::read_to_string(&generated.cpp_header)?;
        let source = std::fs::read_to_string(&generated.cpp_source)?;
        let bridge = std::fs::read_to_string(&generated.cxx_bridge)?;
        let wrapper = std::fs::read_to_string(&generated.rust_wrapper)?;

        assert!(header.contains("void set_packed_bytes(std::uint32_t value) noexcept;"));
        assert!(header.contains("[[nodiscard]] std::uint32_t packed_bytes_out() const noexcept;"));
        assert!(header.contains("[[nodiscard]] std::uint8_t first_byte() const noexcept;"));
        assert!(header.contains("[[nodiscard]] std::uint8_t last_byte() const noexcept;"));
        assert!(!header.contains("rust::Slice<const std::uint32_t> words) noexcept;"));

        assert!(source.contains("PackedArrayPorts::set_packed_bytes("));
        assert!(source.contains("PackedArrayPorts::packed_bytes_out() const noexcept"));

        assert!(
            bridge.contains("fn set_packed_bytes(self: Pin<&mut PackedArrayPorts>, value: u32);")
        );
        assert!(bridge.contains("fn packed_bytes_out(self: &PackedArrayPorts) -> u32;"));

        assert!(wrapper.contains("pub struct PackedBytes {"));
        assert!(wrapper.contains("pub struct PackedBytesOut {"));
        assert!(wrapper.contains("impl ::vvm::PackedValue for PackedBytes {"));
        assert!(wrapper.contains("pub const WIDTH: usize = 32;"));
        assert!(wrapper.contains("pub const LEN: usize = 4;"));
        assert!(wrapper.contains("pub const ELEMENT_WIDTH: usize = 8;"));
        assert!(wrapper.contains("pub const LEFT: i64 = 3;"));
        assert!(wrapper.contains("pub const RIGHT: i64 = 0;"));
        assert!(wrapper.contains("pub fn element(&self, index: i64)"));
        assert!(wrapper.contains("pub fn set_element(&mut self, index: i64, value: u8)"));
        assert!(wrapper.contains("Borrow<PackedBytes>"));
        assert!(wrapper.contains("Result<PackedBytesOut>"));
        assert!(wrapper.contains("PackedLayoutFailed"));
        assert!(wrapper.contains("::vvm::extract_unsigned"));
        assert!(wrapper.contains("::vvm::insert_unsigned"));
        assert!(wrapper.contains("::vvm::PackedLayoutError::range_out_of_bounds("));
        assert!(wrapper.contains("::vvm::PackedLayoutError::invalid_packed_value"));
        assert!(wrapper.contains("let raw = ::vvm::extract_unsigned("));
        assert!(wrapper.contains("let raw: u32 = u32::try_from(raw)"));
        assert!(wrapper.contains("let bits = ::vvm::Bits::<32>::from("));
        assert!(wrapper.contains("Ok(PackedBytesOut::from_bits(bits))"));

        Ok(())
    }

    #[test]
    #[allow(clippy::too_many_lines)]
    fn packed_struct_codegen_generates_newtypes_and_flattened_transfer()
    -> Result<(), Box<dyn std::error::Error>> {
        let metadata = packed_struct_ports_metadata()?;
        let output = tempdir()?;
        let generated = generate(&metadata, "Vpacked_struct_ports", output.path(), None)?;

        let header = std::fs::read_to_string(&generated.cpp_header)?;
        let bridge = std::fs::read_to_string(&generated.cxx_bridge)?;
        let wrapper = std::fs::read_to_string(&generated.rust_wrapper)?;

        assert!(header.contains("void set_packet(std::uint32_t value) noexcept;"));
        assert!(header.contains("[[nodiscard]] std::uint32_t packet_out() const noexcept;"));
        assert!(
            header
                .contains("bool set_wide_packet(rust::Slice<const std::uint32_t> words) noexcept;")
        );
        assert!(
            header
                .contains("bool wide_packet_out(rust::Slice<std::uint32_t> words) const noexcept;")
        );

        assert!(bridge.contains("fn set_packet(self: Pin<&mut PackedStructPorts>, value: u32);"));
        assert!(bridge.contains("fn packet_out(self: &PackedStructPorts) -> u32;"));
        assert!(bridge.contains(
            "fn set_wide_packet(self: Pin<&mut PackedStructPorts>, words: &[u32]) -> bool;"
        ));
        assert!(
            bridge.contains(
                "fn wide_packet_out(self: &PackedStructPorts, words: &mut [u32]) -> bool;"
            )
        );

        assert!(wrapper.contains("pub struct Packet {"));
        assert!(wrapper.contains("pub struct PacketOut {"));
        assert!(wrapper.contains("pub struct WidePacket {"));
        assert!(wrapper.contains("pub struct WidePacketOut {"));
        assert!(wrapper.contains("pub const FIELDS: &'static [::vvm::PackedFieldLayout] = &["));
        assert!(wrapper.contains("pub const LAYOUT: ::vvm::PackedLayout ="));
        assert!(wrapper.contains(
            "pub fn opcode(&self) -> std::result::Result<u8, ::vvm::PackedLayoutError> {"
        ));
        assert!(wrapper.contains(
            "pub fn set_opcode(&mut self, value: u8) -> std::result::Result<(), \
             ::vvm::PackedLayoutError> {"
        ));
        assert!(wrapper.contains(
            "pub fn valid(&self) -> std::result::Result<bool, ::vvm::PackedLayoutError> {"
        ));
        assert!(wrapper.contains(
            "pub fn set_valid(&mut self, value: bool) -> std::result::Result<(), \
             ::vvm::PackedLayoutError> {"
        ));
        assert!(wrapper.contains(
            "pub fn delta(&self) -> std::result::Result<i8, ::vvm::PackedLayoutError> {"
        ));
        assert!(wrapper.contains(
            "pub fn set_delta(&mut self, value: i8) -> std::result::Result<(), \
             ::vvm::PackedLayoutError> {"
        ));
        assert!(wrapper.contains(
            "pub fn payload(&self) -> std::result::Result<u16, ::vvm::PackedLayoutError> {"
        ));
        assert!(wrapper.contains(
            "pub fn set_payload(&mut self, value: u16) -> std::result::Result<(), \
             ::vvm::PackedLayoutError> {"
        ));
        assert!(wrapper.contains(
            "pub fn payload(&self) -> std::result::Result<::vvm::SignedBits<129>, \
             ::vvm::PackedLayoutError> {"
        ));
        assert!(wrapper.contains(
            "pub fn set_payload(&mut self, value: impl \
             ::core::borrow::Borrow<::vvm::SignedBits<129>>) -> std::result::Result<(), \
             ::vvm::PackedLayoutError> {"
        ));
        assert!(wrapper.contains("::vvm::extract_unsigned"));
        assert!(wrapper.contains("::vvm::insert_unsigned"));
        assert!(wrapper.contains("::vvm::extract_signed"));
        assert!(wrapper.contains("::vvm::insert_signed"));
        assert!(wrapper.contains("::vvm::extract_packed::<::vvm::SignedBits<129>>("));
        assert!(wrapper.contains("::vvm::insert_packed("));
        assert!(wrapper.contains("impl ::vvm::PackedValue for Packet {"));
        assert!(wrapper.contains("value: impl ::core::borrow::Borrow<Packet>"));
        assert!(wrapper.contains("pub fn packet_out(&self) -> Result<PacketOut> {"));
        assert!(wrapper.contains("PackedLayoutFailed"));

        Ok(())
    }

    #[test]
    fn preserves_metadata_port_order() -> Result<(), Box<dyn std::error::Error>> {
        let width = BitWidth::new(NonZeroU32::MIN);

        let metadata = DutMetadata {
            name: "ordered".to_owned(),
            top_module: "ordered".to_owned(),
            ports: vec![
                scalar_port("z_input", PortDirection::Input, width, false),
                scalar_port("a_input", PortDirection::Input, width, false),
                scalar_port("m_output", PortDirection::Output, width, false),
            ],
        };

        let output = tempdir()?;
        let generated = generate(&metadata, "Vordered", output.path(), None)?;

        let header = std::fs::read_to_string(generated.cpp_header)?;

        let z_position = header.find("set_z_input").ok_or_else(|| {
            std::io::Error::new(std::io::ErrorKind::InvalidData, "missing set_z_input")
        })?;

        let a_position = header.find("set_a_input").ok_or_else(|| {
            std::io::Error::new(std::io::ErrorKind::InvalidData, "missing set_a_input")
        })?;

        let m_position = header.find("m_output").ok_or_else(|| {
            std::io::Error::new(std::io::ErrorKind::InvalidData, "missing m_output")
        })?;

        assert!(z_position < a_position);
        assert!(a_position < m_position);

        Ok(())
    }
}
