//! Verilator Verification Methodology for Rust.
//!
//! VVM's public API is organized by domain. Import ordinary types from the
//! relevant facade module, such as [`dut`], [`testbench`], or [`coverage`].
//! Derive and attribute macros remain available at the crate root.
//!
//! ```
//! use vvm::coverage::{Bin, Coverpoint, Cross2};
//!
//! let mut value = Coverpoint::builder("value")
//!     .bin(Bin::value("zero", 0_u8))
//!     .build()?;
//! let mut response = Coverpoint::builder("response")
//!     .bin(Bin::value("okay", true))
//!     .build()?;
//! let mut cross = Cross2::builder("value_x_response", &value, &response).build()?;
//! let value_sample = value.sample(&0)?;
//! let response_sample = response.sample(&true)?;
//! assert!(cross.sample(&value_sample, &response_sample)?.hit());
//! # Ok::<(), Box<dyn std::error::Error>>(())
//! ```

/// Standard Rust test-harness bridge used by generated test wrappers.
mod harness;

/// Functional coverage definitions, persistence, reports, and sessions.
pub mod coverage;
/// DUT lifecycle, driving, sampling, and tracing traits.
pub mod dut;
/// Packed bit vectors and packed-layout utilities.
pub mod packed;
/// Common test-authoring imports.
pub mod prelude;
/// Deterministic randomization and replay support.
pub mod random;
/// Registered test execution and reporting APIs.
pub mod test;
/// Cycle-driven testbench, models, and scoreboards.
pub mod testbench;
/// Clocks, simulation time, and timing schedulers.
pub mod timing;

pub use vvm_macros::{Clock, Coverage, Drive, Sample, test};

/// Includes a DUT wrapper generated by `vvm-build`.
#[macro_export]
macro_rules! include_dut {
    ($name:ident $(,)?) => { $crate::include_dut!(mod $name); };
    ($visibility:vis mod $name:ident $(,)?) => {
        #[doc(hidden)]
        extern crate vvm as cxx;

        #[doc = concat!("Generated VVM DUT integration module for `", stringify!($name), "`.")]
        $visibility mod $name {
            include!(concat!(env!("OUT_DIR"), "/vvm/", stringify!($name), "/generated/dut.rs"));
        }
    };
}

/// Generated-source implementation ABI.
///
/// This is public solely because VVM-generated Rust source is compiled inside
/// consuming crates. It is not a supported user-facing API; users must not
/// import it, and its layout may change with generated-code implementations.
#[doc(hidden)]
pub mod __private {
    pub use cxx;
    pub use vvm_core::{
        Bits, Clock, CoverageDefinitionError, CoverageGroupVisitor, CoverageInstance,
        CoverageItemRef, CoverageRuntimeError, CoverageSampleSpec, CoverageSpec, Cross2, Drive,
        Dut, InoutState, IntoTestOutcome, InvalidBitVectorWordCount, ObservedCycle,
        PackedEnumLayout, PackedEnumVariantLayout, PackedFieldLayout, PackedLayout,
        PackedLayoutError, PackedRange, PackedValue, Sample, SignedBits, SimulationTime,
        TestCapabilities, TestContext, TestDescriptor, TestOutcome, TimeStep, TimedDut,
        TraceableDut, UnpackedArrayIndexError, extract_packed, extract_signed,
        extract_signed_packed, extract_unsigned, insert_packed, insert_signed,
        insert_signed_packed, insert_unsigned, unpacked_array_ordinal,
    };

    pub use crate::harness::{TestFailure, run_test};
}

#[doc(hidden)]
pub use cxx::*;
