//! Verilator Verification Methodology for Rust.
//!
//! VVM provides strongly typed Rust testbenches for Verilator-generated HDL
//! models.
//!
//! Tests marked with `#[vvm::test]` become ordinary Rust `#[test]` functions.
//! Place unit-style VVM tests inside an explicit `#[cfg(test)]` module. Cargo
//! integration tests under `tests/` do not need an additional `cfg(test)`.
//! Standard Rust tooling such as `cargo test` and `cargo nextest run` owns test
//! discovery, filtering, and execution.
//!
//! The runtime facade exposes:
//!
//! - generated DUT integration;
//! - typed stimulus driving and output sampling;
//! - synchronous clock control;
//! - stateful reference models;
//! - scoreboards and structured mismatches;
//! - deterministic testbench execution.
//!
//! Native compilation and DUT generation are configured separately through
//! the `vvm-build` crate from a consuming package's `build.rs`.
//!
//! # Example
//!
//! A build script describes the DUT:
//!
//! ```ignore
//! use vvm_build::{BuildResult, DutBuilder};
//!
//! fn main() -> BuildResult<()> {
//!     DutBuilder::new("counter")
//!         .top_module("counter")
//!         .source("rtl/counter.sv")
//!         .build()
//! }
//! ```
//!
//! The generated DUT can then be included and verified:
//!
//! ```ignore
//! #[cfg(test)]
//! mod vvm_tests {
//!     use vvm::prelude::*;
//!
//!     vvm::include_dut!(counter);
//!
//!     use counter::Counter;
//!
//!     #[derive(Clone, Copy, Debug, Drive)]
//!     #[vvm(dut = Counter)]
//!     struct CounterStimulus {
//!         #[vvm(port)]
//!         reset_n: bool,
//!
//!         #[vvm(port)]
//!         enable: bool,
//!     }
//!
//!     #[derive(Clone, Copy, Debug, PartialEq, Eq, Sample)]
//!     #[vvm(dut = Counter)]
//!     struct CounterObservation {
//!         #[vvm(port)]
//!         count: u8,
//!     }
//!
//!     #[derive(Clone, Copy, Debug, Default, Clock)]
//!     #[vvm(
//!         dut = Counter,
//!         clock = "clk"
//!     )]
//!     struct CounterClock;
//!
//!     /// Counter smoke verification.
//!     #[vvm::test(trace)]
//!     fn counter_smoke(config: &vvm::TestRunConfig) -> Result<CounterTestResult> {
//!         let mut dut = Counter::new()?;
//!
//!         config.configure_trace(&mut dut)?;
//!
//!         Ok(
//!             Testbench::new(dut)
//!                 // ...
//!                 .run::<CounterObservation>(),
//!         )
//!     }
//! }
//! ```

/// Standard Rust test harness integration support.
pub(crate) mod test;

#[doc(inline)]
pub use vvm_core::{
    Bits, CheckFailure, Clock, CycleTiming, DetailedTestReport, Drive, Dut, ExactScoreboard,
    FailurePolicy, IntoTestOutcome, InvalidBitVectorWordCount, InvalidFailureLimit,
    InvalidTimeStep, Mismatch, ParseReplayTokenError, RandomAlgorithm, RandomContext, Randomize,
    ReferenceModel, ReplayToken, ReplayableSequence, Sample, Scoreboard, Seed, SignedBits,
    SimulationError, SimulationStage, SimulationTime, TestCapabilities, TestDescriptor,
    TestFunction, TestOutcome, TestRegistry, TestRegistryError, TestResult, TestRun, TestRunConfig,
    TestStatistics, TestStatus, TestSummary, Testbench, TimeStep, TraceableDut,
};
#[doc(inline)]
pub use vvm_macros::{Clock, Drive, Sample, test};

/// Commonly used VVM traits, derives, and testbench types.
///
/// Importing the prelude makes both the methodology traits and derive macros
/// available:
///
/// ```
/// use vvm::prelude::*;
/// ```
pub mod prelude {
    pub use crate::{
        Bits, Clock, CycleTiming, Drive, Dut, ExactScoreboard, FailurePolicy, RandomContext,
        Randomize, ReferenceModel, ReplayableSequence, Sample, Scoreboard, Seed, SignedBits,
        SimulationTime, TestDescriptor, TestRegistryError, TestRunConfig, Testbench, TimeStep,
    };
}

/// Includes a DUT wrapper generated by `vvm-build`.
///
/// The identifier must match the name passed to
/// `vvm_build::DutBuilder::new`.
///
/// The short form creates a private module:
///
/// ```ignore
/// vvm::include_dut!(counter);
///
/// use counter::Counter;
/// ```
///
/// An explicit module visibility may also be supplied:
///
/// ```ignore
/// vvm::include_dut!(pub mod counter);
/// ```
///
/// Multiple DUTs are naturally separated by module:
///
/// ```ignore
/// vvm::include_dut!(counter);
/// vvm::include_dut!(uart);
///
/// use counter::Counter;
/// use uart::Uart;
/// ```
///
/// Manual fallback:
///
/// ```ignore
/// mod counter {
///     include!(concat!(env!("OUT_DIR"), "/vvm/counter/generated/dut.rs"));
/// }
/// ```
#[macro_export]
macro_rules! include_dut {
    ($name:ident $(,)?) => {
        $crate::include_dut!(mod $name);
    };

    ($visibility:vis mod $name:ident $(,)?) => {
        #[doc(hidden)]
        extern crate vvm as cxx;

        #[doc = concat!(
            "Generated VVM DUT integration module for `",
            stringify!($name),
            "`."
        )]
        $visibility mod $name {
            include!(concat!(
                env!("OUT_DIR"),
                "/vvm/",
                stringify!($name),
                "/generated/dut.rs"
            ));
        }
    };
}

/// Implementation dependencies used by VVM-generated source.
///
/// This module is public only because generated source is compiled in the
/// consuming crate. It is not part of the user-facing API.
#[doc(hidden)]
pub mod __private {
    pub use cxx;

    pub use crate::test::{TestFailure, run_test};
}

#[doc(hidden)]
pub use cxx::*;
