[package]
name = "vvm-build"
version.workspace       = true
authors.workspace       = true
edition.workspace       = true
rust-version.workspace  = true
homepage.workspace      = true
repository.workspace    = true
license.workspace       = true
keywords.workspace      = true
categories.workspace    = true
description             = "Build-script integration for Verilator-backed VVM DUT generation"
readme                  = "README.md"
documentation           = "https://byacrates.gitlab.io/vvm-rs/api/vvm_build/"

[lib]
bench = false

[dependencies]
cxx-build.workspace = true
thiserror.workspace = true
serde_json.workspace = true

[dev-dependencies]
criterion.workspace = true
tempfile.workspace = true

[[bench]]
name = "metadata"
harness = false

[[bench]]
name = "build_workflow"
harness = false

[package.metadata.cargo-udeps.ignore]
normal = [
    "vvm",
    "vvm-build",
    "vvm-core",
    "vvm-macros",
]
development = ["criterion"]
