// @generated by vvm-build. Do not edit.

#include "counter.hpp"

#include "Vcounter.h"
#include "verilated.h"
#include "verilated_vcd_c.h"

#include <cstdint>
#include <string>
#include <memory>
#include <type_traits>
#include <limits>

namespace vvm::counter {

class Counter::Impl final {
public:
    Impl()
        : context{std::make_unique<VerilatedContext>()} {
        context->traceEverOn(true);

        model = std::make_unique<Vcounter>(context.get());
        {
            using RawType = std::decay_t<decltype(model->clk)>;
            RawType raw_value{};
            model->clk = raw_value;
        }
        {
            using RawType = std::decay_t<decltype(model->reset_n)>;
            RawType raw_value{};
            model->reset_n = raw_value;
        }
        {
            using RawType = std::decay_t<decltype(model->enable)>;
            RawType raw_value{};
            model->enable = raw_value;
        }
    }

    void dump_trace() noexcept {
        if (trace == nullptr || !trace->isOpen()) {
            return;
        }

        const auto now = context->time();

        if (has_trace_dump && now <= last_trace_time) {
            return;
        }

        trace->dump(now);
        last_trace_time = now;
        has_trace_dump = true;
    }

    void close_trace() noexcept {
        if (trace == nullptr || !trace->isOpen()) {
            return;
        }

        trace->flush();
        trace->close();
    }

    std::unique_ptr<VerilatedContext> context;
    std::unique_ptr<Vcounter> model;
    std::unique_ptr<VerilatedVcdC> trace;
    std::uint64_t last_trace_time{0};
    bool has_trace_dump{false};
    bool finished{false};
};

Counter::Counter()
    : impl_{std::make_unique<Impl>()} {}

Counter::~Counter() noexcept {
    finish();
}

void Counter::eval() noexcept {
    if (impl_->finished) {
        return;
    }

    impl_->model->eval();
    impl_->dump_trace();
}

void Counter::finish() noexcept {
    if (impl_->finished) {
        return;
    }

    impl_->model->final();

    impl_->dump_trace();
    impl_->close_trace();

    impl_->finished = true;
}

bool Counter::open_trace(
    const rust::Str path
) noexcept {
    if (impl_->finished || impl_->trace != nullptr) {
        return false;
    }

    try {
        impl_->trace = std::make_unique<VerilatedVcdC>();

        impl_->model->trace(impl_->trace.get(), 99);

        const std::string filename{path};

        impl_->trace->open(filename.c_str());

        return impl_->trace->isOpen();
    } catch (...) {
        return false;
    }
}

void Counter::close_trace() noexcept {
    impl_->close_trace();
}

bool Counter::trace_is_open() const noexcept {
    return impl_->trace != nullptr && impl_->trace->isOpen();
}

void Counter::set_clk(const bool value) noexcept {
    using RawType = std::decay_t<decltype(impl_->model->clk)>;

    RawType raw_value{static_cast<RawType>(value)};
    impl_->model->clk = raw_value;
}

void Counter::set_reset_n(const bool value) noexcept {
    using RawType = std::decay_t<decltype(impl_->model->reset_n)>;

    RawType raw_value{static_cast<RawType>(value)};
    impl_->model->reset_n = raw_value;
}

void Counter::set_enable(const bool value) noexcept {
    using RawType = std::decay_t<decltype(impl_->model->enable)>;

    RawType raw_value{static_cast<RawType>(value)};
    impl_->model->enable = raw_value;
}

std::uint8_t Counter::count() const noexcept {
    return static_cast<std::uint8_t>(impl_->model->count);
}

bool Counter::advance_time(
    const std::uint64_t delta
) noexcept {
    const auto current = impl_->context->time();

    if (delta > std::numeric_limits<std::uint64_t>::max() - current) {
        return false;
    }

    impl_->context->timeInc(delta);

    return true;
}

std::unique_ptr<Counter> create_counter() noexcept {
    try {
        return std::make_unique<Counter>();
    } catch (...) {
        return nullptr;
    }
}

} // namespace vvm::counter
