// @generated by vvm-build. Do not edit.

include!(concat!(
    env!("OUT_DIR"),
    "/vvm/counter/generated/bridge.rs"
));

/// Compact generated trace-state flag.
#[derive(Clone, Copy, Default, PartialEq, Eq)]
struct TraceFlag(bool);

impl TraceFlag {
    /// Creates a flag from a raw boolean state.
    const fn new(value: bool) -> Self {
        Self(value)
    }

    /// Returns whether the flag is currently set.
    const fn is_set(self) -> bool {
        self.0
    }
}

impl std::fmt::Debug for TraceFlag {
    fn fmt(
        &self,
        formatter: &mut std::fmt::Formatter<'_>,
    ) -> std::fmt::Result {
        self.0.fmt(formatter)
    }
}

/// Error returned by generated DUT operations.
#[allow(dead_code)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CounterError {
    /// The native Verilated model could not be constructed.
    ConstructionFailed,

    /// The operation requires a DUT that has not been finished.
    Finished,

    /// The internal native adapter is unexpectedly unavailable.
    AdapterUnavailable,

    /// Simulation time would overflow.
    TimeOverflow,

    /// Trace configuration was requested after evaluation began.
    TraceAfterEvaluation,

    /// A waveform trace has already been configured.
    TraceAlreadyConfigured,

    /// The waveform trace path is not valid UTF-8.
    TracePathNotUtf8,

    /// The native waveform trace could not be opened.
    TraceOpenFailed,
}

impl std::fmt::Display for CounterError {
    fn fmt(
        &self,
        formatter: &mut std::fmt::Formatter<'_>,
    ) -> std::fmt::Result {
        let message = match *self {
            Self::ConstructionFailed => "failed to construct the Verilated counter model",
            Self::Finished => "the counter model has already been finished",
            Self::AdapterUnavailable => "the counter native adapter is unexpectedly unavailable",
            Self::TimeOverflow => "advancing counter simulation time would overflow",
            Self::TraceAfterEvaluation => {"waveform tracing must be configured before the first evaluation"},
            Self::TraceAlreadyConfigured => {"waveform tracing has already been configured for this DUT"},
            Self::TracePathNotUtf8 => {"waveform trace path is not valid UTF-8"},
            Self::TraceOpenFailed => {"failed to open the native VCD waveform trace"}
        };

        formatter.write_str(message)
    }
}

impl std::error::Error for CounterError {}

/// Result type returned by generated DUT operations.
pub type Result<T> = std::result::Result<T, CounterError>;

/// Safe Rust wrapper for the `counter` Verilated DUT.
pub struct Counter {
    /// Opaque ownership of the generated C++ adapter.
    inner: ::vvm::__private::cxx::UniquePtr<ffi::Counter>,

    /// Tracks whether finalisation has already completed.
    finished: bool,

    /// Current logical simulation time.
    time: ::vvm::__private::SimulationTime,

    /// Whether the DUT has been evaluated.
    evaluated: TraceFlag,

    /// Whether trace configuration has been attempted.
    trace_configured: TraceFlag,

    /// Whether the native trace is currently open.
    trace_open: TraceFlag,
}

#[allow(dead_code)]
#[allow(clippy::same_name_method)]
impl Counter {
    /// Constructs the Verilated DUT.
    ///
    /// # Errors
    ///
    /// Returns an error when the native adapter cannot be constructed.
    pub fn new() -> Result<Self> {
        let inner = ffi::create_counter();

        Self::from_inner(inner)
    }

    /// Constructs Verilated DUT from an internal [`::vvm::__private::cxx::UniquePtr`].
    fn from_inner(inner: ::vvm::__private::cxx::UniquePtr<ffi::Counter>) -> Result<Self> {
        if inner.is_null() {
            return Err(CounterError::ConstructionFailed);
        }

        Ok(Self {
            inner,
            finished: false,
            time: ::vvm::__private::SimulationTime::ZERO,
            evaluated: TraceFlag::new(false),
            trace_configured: TraceFlag::new(false),
            trace_open: TraceFlag::new(false),
        })
    }

    /// Returns whether the DUT has been finalised.
    #[must_use]
    pub const fn is_finished(&self) -> bool {
        self.finished
    }

    /// Evaluates the current DUT state.
    ///
    /// # Errors
    ///
    /// Returns an error if the DUT has already been finished.
    pub fn eval(&mut self) -> Result<()> {
        self.ensure_running()?;
        self.inner_mut()?.eval();
        self.evaluated = TraceFlag::new(true);

        Ok(())
    }

    /// Opens the generated VCD waveform trace.
    ///
    /// This must be called before the first DUT evaluation.
    ///
    /// # Errors
    ///
    /// Returns an error if the DUT is finished, has already been evaluated,
    /// tracing was previously configured, the path is not valid UTF-8, or the
    /// native trace file cannot be opened.
    pub fn open_trace(
        &mut self,
        path: &std::path::Path,
    ) -> Result<()> {
        self.ensure_running()?;

        if self.evaluated.is_set() {
            return Err(CounterError::TraceAfterEvaluation);
        }

        if self.trace_configured.is_set() {
            return Err(CounterError::TraceAlreadyConfigured);
        }

        let path = path.to_str().ok_or(
            CounterError::TracePathNotUtf8,
        )?;

        let opened =
            self.inner_mut()?.open_trace(path);

        self.trace_configured = TraceFlag::new(true);

        if !opened {
            return Err(CounterError::TraceOpenFailed);
        }

        self.trace_open = TraceFlag::new(self.inner_ref()?.trace_is_open());

        Ok(())
    }

    /// Flushes and closes the active waveform trace.
    ///
    /// Repeated calls are safe.
    ///
    /// # Errors
    ///
    /// Returns an error if the native adapter is unexpectedly unavailable.
    pub fn close_trace(&mut self) -> Result<()> {
        if self.finished {
            self.trace_open = TraceFlag::new(false);
            return Ok(());
        }

        self.inner_mut()?.close_trace();
        self.trace_open = TraceFlag::new(self.inner_ref()?.trace_is_open());

        Ok(())
    }

    /// Returns whether the waveform trace is currently open.
    #[must_use]
    pub const fn trace_is_open(&self) -> bool {
        self.trace_open.is_set()
    }

    /// Finalises the DUT exactly once.
    ///
    /// Calling this method repeatedly is safe.
    ///
    /// # Errors
    ///
    /// Returns an error if the native adapter is unexpectedly unavailable.
    pub fn finish(&mut self) -> Result<()> {
        if self.finished {
            return Ok(());
        }

        self.inner_mut()?.finish();
        self.trace_open = TraceFlag::new(false);
        self.finished = true;

        Ok(())
    }
    /// Returns the current simulation time.
    #[must_use]
    const fn simulation_time_value(
        &self,
    ) -> ::vvm::__private::SimulationTime {
        self.time
    }
    /// Advances the simulation time without evaluating the DUT.
    ///
    /// # Errors
    ///
    /// Returns an error if the DUT is finished, the adapter is unavailable, or
    /// the resulting time would overflow.
    fn advance_time_inner(
        &mut self,
        delta: ::vvm::__private::TimeStep,
    ) -> Result<()> {
        self.ensure_running()?;
        let Some(next_time) =
            self.time.checked_add(delta)
        else {
            return Err(CounterError::TimeOverflow);
        };
        let advanced = self
            .inner_mut()?
            .advance_time(delta.ticks());
        if !advanced {
            return Err(CounterError::TimeOverflow);
        }
        self.time = next_time;
        Ok(())
    }

    /// Drives the `clk` DUT input.
    ///
    /// The value may be supplied by value or by reference.
    ///
    /// # Errors
    ///
    /// Returns an error if the DUT has already been finished.
    #[allow(clippy::needless_pass_by_value)]
    pub fn set_clk(
        &mut self,
        value: impl ::core::borrow::Borrow<bool>,
    ) -> Result<()> {
        self.ensure_running()?;

        let value: bool =
            *::core::borrow::Borrow::borrow(&value);

        self.inner_mut()?.set_clk(value);

        Ok(())
    }

    /// Drives the `reset_n` DUT input.
    ///
    /// The value may be supplied by value or by reference.
    ///
    /// # Errors
    ///
    /// Returns an error if the DUT has already been finished.
    #[allow(clippy::needless_pass_by_value)]
    pub fn set_reset_n(
        &mut self,
        value: impl ::core::borrow::Borrow<bool>,
    ) -> Result<()> {
        self.ensure_running()?;

        let value: bool =
            *::core::borrow::Borrow::borrow(&value);

        self.inner_mut()?.set_reset_n(value);

        Ok(())
    }

    /// Drives the `enable` DUT input.
    ///
    /// The value may be supplied by value or by reference.
    ///
    /// # Errors
    ///
    /// Returns an error if the DUT has already been finished.
    #[allow(clippy::needless_pass_by_value)]
    pub fn set_enable(
        &mut self,
        value: impl ::core::borrow::Borrow<bool>,
    ) -> Result<()> {
        self.ensure_running()?;

        let value: bool =
            *::core::borrow::Borrow::borrow(&value);

        self.inner_mut()?.set_enable(value);

        Ok(())
    }

    /// Samples the `count` DUT output.
    ///
    /// # Errors
    ///
    /// Returns an error if the DUT has already been finished.
    pub fn count(&self) -> Result<u8> {
        self.ensure_running()?;

        Ok(self.inner_ref()?.count())
    }

    /// Ensures that operations may still access the DUT.
    const fn ensure_running(&self) -> Result<()> {
        if self.finished {
            return Err(CounterError::Finished);
        }

        Ok(())
    }

    /// Returns an immutable reference to the native adapter.
    fn inner_ref(&self) -> Result<&ffi::Counter> {
        self.inner.as_ref().ok_or(
            CounterError::AdapterUnavailable,
        )
    }

    /// Returns a pinned mutable reference to the native adapter.
    fn inner_mut(&mut self) -> Result<std::pin::Pin<&mut ffi::Counter>> {
        self.inner.as_mut().ok_or(
            CounterError::AdapterUnavailable,
        )
    }
}

impl std::fmt::Debug for Counter {
    fn fmt(
        &self,
        formatter: &mut std::fmt::Formatter<'_>,
    ) -> std::fmt::Result {
        formatter.debug_struct("Counter")
            .field("finished", &self.finished)
            .field("time", &self.time)
            .field("evaluated", &self.evaluated)
            .field("trace_configured", &self.trace_configured)
            .field("trace_open", &self.trace_open)
            .finish_non_exhaustive()
    }
}

impl ::vvm::__private::Dut for Counter {
    type Error = CounterError;

    fn evaluate(&mut self) -> Result<()> {
        Self::eval(self)
    }

    fn finalize(&mut self) -> Result<()> {
        Self::finish(self)
    }
    fn simulation_time(
        &self,
    ) -> ::vvm::__private::SimulationTime {
        Self::simulation_time_value(self)
    }
    fn advance_time(
        &mut self,
        delta: ::vvm::__private::TimeStep,
    ) -> Result<()> {
        Self::advance_time_inner(self, delta)
    }
}

#[allow(clippy::same_name_method)]
impl ::vvm::__private::TraceableDut for Counter {
    fn open_trace(
        &mut self,
        path: &std::path::Path,
    ) -> Result<()> {
        Self::open_trace(self, path)
    }

    fn close_trace(
        &mut self,
    ) -> Result<()> {
        Self::close_trace(self)
    }

    fn trace_is_open(&self) -> bool {
        Self::trace_is_open(self)
    }
}

impl Drop for Counter {
    fn drop(&mut self) {
        if self.finished {
            return;
        }

        if let Some(inner) = self.inner.as_mut() {
            inner.finish();
        }

        self.trace_open = TraceFlag::new(false);
        self.finished = true;
    }
}
