[package]
name = "vvm-example-sync-fifo"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false
build = "build.rs"
description = "Synchronous FIFO verification example for VVM"

[lib]
bench = false

[lints]
workspace = true

[dependencies]
thiserror.workspace = true
vvm.workspace = true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "sync_fifo"
harness = false

[build-dependencies]
vvm-build.workspace = true
